import { test, expect } from '@playwright/test';

test('configure paired Bloch faces and custom PML, run complex fields',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.getByLabel('y min bc',{exact:true}).selectOption('bloch');
 await expect(page.getByLabel('y max bc',{exact:true})).toHaveValue('bloch');
 await page.getByLabel('Bloch phase y',{exact:true}).fill('0.4');
 await page.getByLabel('Bloch phase y',{exact:true}).press('Tab');
 await page.getByText('x min PML settings',{exact:true}).click();
 await expect(page.locator('[data-path="boundaries.x_min.alpha"]')).toHaveValue('1e-8');
 await page.getByLabel('x min layers',{exact:true}).fill('14');
 await page.getByLabel('x min layers',{exact:true}).press('Tab');
 await expect(page.locator('[data-boundary-default="x_min"]')).not.toBeChecked();
 await page.getByLabel('field display',{exact:true}).selectOption('imag');
 await page.getByLabel('time steps',{exact:true}).fill('500');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.screenshot({path:'results/ui-boundaries.png',fullPage:true});
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const key=(await (await submitted).json()).id;
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:45000});
 await expect(page.locator('#results-tree')).toContainText('field snapshots');
 await expect(page.locator('#field-label')).toContainText('imag');
 const job=await (await page.request.get('/api/jobs/'+key)).json();
 expect(job.status).toBe('completed');expect(job.summary.complex_fields).toBe(true);
 if(process.env.TORCHFDTD_TEST_CUDA)expect(job.summary.cuda_graph).toBe(true);
 expect(job.summary.boundaries.x_min.layers).toBe(14);
 expect(job.monitors.every(m=>m.complex)).toBe(true);
 const csv=await (await page.request.get('/api/jobs/'+key+'/monitors.csv')).text();
 expect(csv).toContain('reduced_field_imag');
 await page.screenshot({path:'results/ui-bloch-result.png',fullPage:true});
 expect(errors).toEqual([]);
});
