import { test, expect } from '@playwright/test';

test('import a real global frequency-range FSP and execute independently on GPU',async({page})=>{
 test.skip(!process.env.PHOTONWEAVE_BROADBAND_FSP,'Requires a controlled broadband layout fixture');
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="fsp-native"]').click();
 if(process.env.PHOTONWEAVE_DC_FSP){
  await page.locator('#fsp-native-input').setInputFiles(process.env.PHOTONWEAVE_DC_FSP);
  await expect(page.locator('.native-issues')).toContainText('Eliminate-DC',{timeout:20000});
  await expect(page.locator('[data-native="load"]')).toBeDisabled();
 }
 await page.locator('#fsp-native-input').setInputFiles(process.env.PHOTONWEAVE_BROADBAND_FSP);
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();
 await expect(page.locator('#fsp-native-dialog')).not.toBeVisible();
 await page.locator('#tree .source-row').click();
 await expect(page.getByLabel('Use global source settings',{exact:true})).toBeChecked();
 await expect(page.getByLabel('time definition',{exact:true})).toHaveValue('frequency');
 await expect(page.getByLabel('frequency start',{exact:true})).toBeDisabled();
 await expect(page.locator('[data-source-band-summary]')).toContainText('0.99202 µm');
 await expect(page.getByLabel('phase',{exact:true})).toHaveValue('-51');
 await page.screenshot({path:'results/ui-broadband-fsp.png',fullPage:true});
 await page.locator('#run-button').click();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:45000});
 await expect(page.locator('.run-summary')).toContainText('CUDA graph');
 await expect(page.locator('.run-summary')).toContainText('5880');
 expect(errors).toEqual([]);
});

test('automatic source wavelength/frequency range, global inheritance and GPU calculation',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.getByLabel('time steps',{exact:true}).fill('1200');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.PHOTONWEAVE_TEST_CUDA?'cuda':'cpu');
 await page.locator('[data-select="source"]').click();
 await page.getByLabel('pulse',{exact:true}).selectOption('broadband');
 await page.getByLabel('wavelength start',{exact:true}).fill('1.2');await page.getByLabel('wavelength start',{exact:true}).press('Tab');
 await page.getByLabel('wavelength stop',{exact:true}).fill('1.8');await page.getByLabel('wavelength stop',{exact:true}).press('Tab');
 await page.getByLabel('Optimize for short pulse',{exact:true}).uncheck();
 await expect(page.locator('[data-source-band-summary]')).toContainText('31.8101 fs');
 await page.getByRole('button',{name:'Preview time signal / spectrum',exact:true}).click();
 const dialog=page.locator('.source-dialog');
 await expect(dialog).toContainText('Chirped carrier');
 await expect(dialog).toContainText('center 1.44000 µm');
 await page.screenshot({path:'results/ui-broadband-preview.png',fullPage:true});
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByLabel('time definition',{exact:true}).selectOption('frequency');
 await expect(page.getByLabel('frequency start',{exact:true})).toHaveValue('166.551365556');
 await page.getByLabel('frequency start',{exact:true}).fill('180');await page.getByLabel('frequency start',{exact:true}).press('Tab');
 await page.getByLabel('frequency stop',{exact:true}).fill('240');await page.getByLabel('frequency stop',{exact:true}).press('Tab');
 await page.getByLabel('time definition',{exact:true}).selectOption('wavelength');
 await expect(page.getByLabel('wavelength start',{exact:true})).toHaveValue('1.24913524167');
 await page.getByRole('button',{name:'Edit global source settings',exact:true}).click();
 await page.getByLabel('global pulse',{exact:true}).selectOption('broadband');
 await page.getByLabel('global time definition',{exact:true}).selectOption('frequency');
 await page.getByLabel('global frequency start',{exact:true}).fill('190');await page.getByLabel('global frequency start',{exact:true}).press('Tab');
 await page.getByLabel('global frequency stop',{exact:true}).fill('210');await page.getByLabel('global frequency stop',{exact:true}).press('Tab');
 await expect(dialog.locator('[data-source-band-summary]')).toContainText('Standard Gaussian');
 await page.getByRole('button',{name:'Apply global settings',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await page.getByLabel('Use global source settings',{exact:true}).check();
 await expect(page.getByLabel('frequency start',{exact:true})).toHaveValue('190');
 await expect(page.getByLabel('frequency start',{exact:true})).toBeDisabled();
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const key=(await (await submitted).json()).id;
 await expect(page.locator('#results-tree')).toContainText('field snapshots',{timeout:45000});
 const job=await (await page.request.get('/api/jobs/'+key)).json();
 expect(job.project.global_source.time_definition).toBe('frequency');
 expect(job.project.sources[0].use_global_source).toBe(true);
 expect(job.monitors[0].signal.some(v=>Math.abs(v)>1e-4)).toBe(true);
 if(process.env.PHOTONWEAVE_TEST_CUDA)expect(job.summary.cuda_graph).toBe(true);
 await page.locator('#layout-button').click();
 await page.getByLabel('Use global source settings',{exact:true}).uncheck();
 await expect(page.getByLabel('wavelength start',{exact:true})).toHaveValue('1.24913524167');
 await page.reload();await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-select="source"]').click();
 await expect(page.getByLabel('pulse',{exact:true})).toHaveValue('broadband');
 expect(errors).toEqual([]);
});
