import {test,expect} from '@playwright/test';

test('GPU switch, memory modes, execution status line and a small Auto run',async({page})=>{
 const health=await (await page.request.get('/api/health')).json();
 expect(typeof health.cupy).toBe('boolean');
 expect(typeof health.host_available_bytes).toBe('number');
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-example="3d"]').click();
 await expect(page.getByLabel('dimension',{exact:true})).toHaveValue('3d');
 const gpu=page.getByLabel('GPU',{exact:true}),memory=page.getByLabel('memory',{exact:true}),status=page.locator('#execution-status');
 const resource=page.getByLabel('resource',{exact:true}),kernel=page.getByLabel('CUDA kernel',{exact:true}),monitorKernel=page.getByLabel('Frequency monitor kernel',{exact:true});
 await expect(memory).toHaveValue('auto');
 await expect(status).toContainText('Auto →');
 if(!health.cuda){
  await expect(gpu).toBeDisabled();
  await expect(gpu).not.toBeChecked();
  await expect(page.locator('.switch-row')).toHaveAttribute('title',/No CUDA device/);
  await expect(status).toContainText('Resident on CPU');
 }else{
  expect(typeof health.gpu_free_bytes).toBe('number');
  await expect(gpu).toBeEnabled();
  await expect(gpu).toBeChecked();
  await gpu.uncheck();
  await expect(resource).toHaveValue('cpu');
  await expect(kernel).toHaveValue('torch');
  await gpu.check();
  await expect(resource).toHaveValue('cuda');
  await expect(kernel).toHaveValue(health.cupy?'fused':'torch');
  await expect(monitorKernel).toHaveValue(health.cupy?'fused':'torch');
  await expect(status).toContainText('Auto → Resident on GPU');
  await expect(status).toContainText('free device memory');
  await gpu.uncheck();
  await expect(resource).toHaveValue('cpu');
 }
 await expect(status).toContainText('Auto → Resident on CPU');
 await expect(status).toContainText('80% of available host memory');
 await memory.selectOption('resident');
 await expect(status).toContainText('Resident on CPU');
 await expect(status).not.toContainText('Auto');
 await memory.selectOption('streamed_host');
 await expect(status).toContainText('Streamed through host memory on CPU');
 await expect(status).toContainText('host reservation');
 await expect(status).toContainText('slab 32 x depth 4');
 await memory.selectOption('streamed_disk');
 await expect(status).toContainText('Streamed through disk on CPU');
 await expect(status).toContainText('disk banks');
 await expect(status).toContainText('scratch');
 await memory.selectOption('auto');
 await expect(status).toContainText('Auto → Resident on CPU');
 await page.locator('[data-advanced-toggle]').click();
 await expect(page.locator('.advanced-execution')).toHaveClass(/open/);
 await expect(page.locator('.advanced-execution .advanced-body')).not.toHaveAttribute('inert');
 await resource.selectOption('cpu');
 await expect(gpu).not.toBeChecked();
 await page.getByLabel('time steps',{exact:true}).fill('120');
 await page.getByLabel('time steps',{exact:true}).press('Tab');
 await expect(status).toContainText('Auto → Resident on CPU');
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();
 const response=await submitted,body=response.request().postDataJSON();
 expect(body.region.execution_mode).toBe('auto');
 expect(body.region.backend).toBe('cpu');
 const job=await response.json();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 await expect(page.locator('.run-summary')).toContainText('Resident');
 await expect(page.locator('.run-summary')).toContainText('estimate');
 const result=await (await page.request.get('/api/jobs/'+job.id)).json();
 expect(result.execution.requested).toBe('auto');
 expect(result.execution.mode).toBe('resident');
 expect(result.execution.resident.fits).toBe(true);
 expect(result.summary.backend).toBe('cpu');
 expect(result.summary.steps).toBe(120);
 await page.screenshot({path:'results/ui-execution-modes.png',fullPage:true});
 expect(errors).toEqual([]);
});

test('streamed host run reports its policy, progress and one final snapshot',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-example="3d"]').click();
 await expect(page.getByLabel('dimension',{exact:true})).toHaveValue('3d');
 const gpu=page.getByLabel('GPU',{exact:true});
 if(await gpu.isEnabled())await gpu.uncheck();
 await expect(page.getByLabel('resource',{exact:true})).toHaveValue('cpu');
 await page.getByLabel('time steps',{exact:true}).fill('120');
 await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('memory',{exact:true}).selectOption('streamed_host');
 await expect(page.locator('#execution-status')).toContainText('Streamed through host memory on CPU');
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();
 const job=await (await submitted).json();
 const seen=new Set();
 await expect.poll(async()=>{seen.add(await page.locator('#status-text').innerText());return page.locator('#mode-badge').innerText();},{timeout:120000,intervals:[50]}).toBe('ANALYSIS');
 expect([...seen].some(text=>/Streaming block \d+ \/ 30 · tile \d+ \/ \d+/.test(text))).toBe(true);
 const summary=page.locator('.run-summary');
 await expect(summary).toContainText('Streamed through host memory');
 await expect(summary).toContainText('slab 32 × depth 4');
 await expect(summary).toContainText('DRAM banks');
 await expect(summary).toContainText('CPU tiles');
 await expect(summary).toContainText('host ');
 await expect(page.locator('#frame-label')).toHaveText('Step 120');
 await expect(page.locator('#messages')).toContainText('Execution: Streamed through host memory (slab 32 × depth 4, host banks)');
 const result=await (await page.request.get('/api/jobs/'+job.id)).json();
 expect(result.execution.mode).toBe('streamed_host');
 expect(result.execution.policy.checkpoints).toBe(0);
 expect(result.execution.policy.state_storage).toBe('host');
 expect(result.execution.report.blocks).toBe(30);
 expect(result.execution.report.completed_blocks).toBe(30);
 expect(result.summary.execution.snapshot).toBe('final step only');
 const fields=await (await page.request.get('/api/jobs/'+job.id+'/fields')).json();
 expect(fields.frame_steps).toEqual([120]);
 expect(result.monitors[0].signal.length).toBe(120);
 expect(errors).toEqual([]);
});
