import {test,expect} from '@playwright/test';

test('feature audit and global/custom frequency plane run without page errors',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="capabilities"]').click();
 const checklist=page.locator('.capability-dialog');
 await expect(checklist).toBeVisible();await expect(checklist.locator('thead')).toContainText('Python');
 await checklist.getByLabel('Search capabilities').fill('Adjoint');
 await expect(checklist.locator('tbody')).toContainText('미구현');
 await checklist.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('[data-add="field"]').click();
 await expect(page.locator('#properties')).toContainText('Frequency / flux monitor');
 await page.getByLabel('sample spacing',{exact:true}).selectOption('custom');
 await page.getByLabel('Custom frequencies (THz)',{exact:true}).fill('180\n200\n220');
 await page.getByLabel('Custom frequencies (THz)',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'Edit global monitor settings',exact:true}).click();
 const globals=page.locator('.monitor-dialog');
 await globals.getByLabel('sample spacing',{exact:true}).selectOption('custom');
 await globals.getByLabel('Custom frequencies (THz)',{exact:true}).fill('190\n210');
 await globals.getByLabel('Custom frequencies (THz)',{exact:true}).press('Tab');
 await globals.getByRole('button',{name:'Apply monitor settings'}).click();
 await expect(globals).not.toBeVisible();
 await page.getByLabel('Use global monitor settings',{exact:true}).check();
 await expect(page.locator('#properties').getByLabel('Custom frequencies (THz)',{exact:true})).toBeDisabled();
 await page.locator('[data-select="fdtd"]').click();
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.getByLabel('time steps',{exact:true}).fill('100');
 await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.locator('#run-button').click();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:45000});
 await page.locator('[data-action="flux-results"]').first().click();
 await expect(globals).toContainText('2 frequencies');
 await expect(globals.locator('canvas')).toBeVisible();
 const csv=await page.request.get(await globals.getByRole('link',{name:'Export raw flux CSV'}).getAttribute('href'));
 expect(await csv.text()).toContain('flux');
 await page.screenshot({path:'results/ui-frequency-flux.png',fullPage:true});
 expect(errors).toEqual([]);
});
