import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';

test('independent polygon import, native edit and verified geometry download',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const python=process.env.PHOTONWEAVE_TEST_PYTHON||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
 const raw=Buffer.from(execFileSync(python,['-c',"import sys,base64;sys.path.insert(0,'tests');from test_fsp_geometry_write import shape_fixture;print(base64.b64encode(shape_fixture()).decode())"],{encoding:'utf8'}).trim(),'base64');
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="fsp-native"]').click();
 await page.locator('#fsp-native-input').setInputFiles({name:'synthetic-polygon.fsp',mimeType:'application/octet-stream',buffer:raw});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();
 await page.locator('#tree .tree-row').filter({hasText:'polygon'}).click();
 await page.getByLabel('x',{exact:true}).fill('0.32');await page.getByLabel('x',{exact:true}).press('Tab');
 await page.getByLabel('rotation 2',{exact:true}).fill('-27');await page.getByLabel('rotation 2',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'Edit polygon vertices',exact:true}).click();
 const editor=page.locator('.geometry-dialog');
 await editor.getByLabel('Polygon vertices',{exact:true}).fill('0,0\n.6,0\n.2,.5');
 await editor.getByRole('button',{name:'Apply vertices',exact:true}).click();await expect(editor).not.toBeVisible();
 await page.locator('[data-action="fsp-native"]').click();await page.locator('[data-native="export"]').click();
 await expect(page.locator('#fsp-native-status')).toContainText('Scene export verified',{timeout:20000});
 const download=page.waitForEvent('download');await page.locator('[data-native="edited"]').click();
 const bytes=fs.readFileSync(await (await download).path());expect(bytes.equals(raw)).toBe(false);
 const reportEvent=page.waitForEvent('download');await page.locator('[data-native="write-report"]').click();
 const report=JSON.parse(fs.readFileSync(await (await reportEvent).path(),'utf8'));
 expect(report.requires_lumerical).toBe(false);expect(report.edits.length).toBeGreaterThan(2);
 const originalEvent=page.waitForEvent('download');await page.locator('[data-native="original"]').click();
 expect(fs.readFileSync(await (await originalEvent).path())).toEqual(raw);
 await page.screenshot({path:'results/ui-fsp-geometry-export.png',fullPage:true});
 // Reimport through the normal UI so the new fingerprint and shifted IDs are used.
 await page.locator('#fsp-native-input').setInputFiles({name:'edited-polygon.fsp',mimeType:'application/octet-stream',buffer:bytes});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();
 const scene=await page.evaluate(()=>JSON.parse(localStorage.getItem('photonweave.project.v1')));
 expect(scene.structures[0].vertices).toHaveLength(3);expect(scene.structures[0].center[0]).toBeCloseTo(.32);
 expect(scene.structures[0].rotation_angles[1]).toBe(-27);
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.PHOTONWEAVE_TEST_CUDA?'cuda':'cpu');
 await page.locator('#run-button').click();await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 if(process.env.PHOTONWEAVE_TEST_CUDA)await expect(page.locator('.run-summary')).toContainText('5880');
 expect(errors).toEqual([]);
});
