import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';

test('add, duplicate and remove FSP sources and monitors, export and run the GPU scene',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const python=process.env.PHOTONWEAVE_TEST_PYTHON||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
 const raw=Buffer.from(execFileSync(python,['-c',"import sys,base64;sys.path.insert(0,'tests');from test_fsp_settings_write import settings_fixture;print(base64.b64encode(settings_fixture()).decode())"],{encoding:'utf8'}).trim(),'base64');
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="fsp-native"]').click();
 await page.locator('#fsp-native-input').setInputFiles({name:'authored-instruments.fsp',mimeType:'application/octet-stream',buffer:raw});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();await expect(page.locator('#fsp-native-dialog')).not.toBeVisible();
 await page.getByLabel('time steps',{exact:true}).fill('80');await page.getByLabel('time steps',{exact:true}).press('Tab');
 const original=await page.evaluate(()=>JSON.parse(localStorage.getItem('photonweave.project.v1')));
 await page.locator('#tree .source-row').click();await page.locator('[data-action="duplicate"]').click();
 await page.locator('#tree .tree-row').filter({hasText:new RegExp('^'+original.sources[0].name+'$')}).click();
 await page.locator('[data-action="delete"]').click();
 await page.locator('[data-add="point"]').click();
 await expect(page.getByLabel('time definition',{exact:true})).toHaveValue('standard');
 await page.getByLabel('pulselength (power FWHM)',{exact:true}).fill('4');await page.getByLabel('pulselength (power FWHM)',{exact:true}).press('Tab');
 await page.getByLabel('offset',{exact:true}).fill('7');await page.getByLabel('offset',{exact:true}).press('Tab');
 await page.locator('#tree .tree-row').filter({hasText:new RegExp('^'+original.monitors[0].name+'$')}).click();
 await page.locator('[data-action="duplicate"]').click();
 await page.locator('#tree .tree-row').filter({hasText:new RegExp('^'+original.monitors[0].name+'$')}).click();
 await page.locator('[data-action="delete"]').click();
 await page.locator('[data-add="monitor"]').click();
 await expect(page.getByLabel('apodization',{exact:true})).toHaveValue('none');
 await page.locator('[data-add="field"]').click();
 const expected=await page.evaluate(()=>JSON.parse(localStorage.getItem('photonweave.project.v1')));
 expect(expected.sources).toHaveLength(2);expect(expected.monitors).toHaveLength(3);
 await page.locator('[data-action="fsp-native"]').click();await page.locator('[data-native="export"]').click();
 await expect(page.locator('#fsp-native-status')).toContainText('Scene export verified',{timeout:20000});
 await expect(page.locator('[data-native-source-export]')).toContainText('2 added · 1 removed · 2 total');
 await expect(page.locator('[data-native-monitor-export]')).toContainText('3 added · 1 removed · 3 outputs');
 const event=page.waitForEvent('download');await page.locator('[data-native="edited"]').click();
 const bytes=fs.readFileSync(await (await event).path());
 const reportEvent=page.waitForEvent('download');await page.locator('[data-native="write-report"]').click();
 const report=JSON.parse(fs.readFileSync(await (await reportEvent).path(),'utf8'));
 expect(report.source_list.added).toHaveLength(2);expect(report.monitor_list.added).toHaveLength(3);
 await page.screenshot({path:'results/ui-fsp-instruments-export.png',fullPage:true});
 await page.locator('#fsp-native-input').setInputFiles({name:'edited-instruments.fsp',mimeType:'application/octet-stream',buffer:bytes});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();await expect(page.locator('#fsp-native-dialog')).not.toBeVisible();
 const actual=await page.evaluate(()=>JSON.parse(localStorage.getItem('photonweave.project.v1')));
 for(const key of ['structures','sources','monitors'])expect(actual[key].map(o=>o.id)).toEqual(expected[key].map(o=>report.id_mapping[o.id]));
 expect(actual.sources.map(s=>s.name)).toEqual(expected.sources.map(s=>s.name));
 expect(actual.monitors.map(m=>m.name)).toEqual(expected.monitors.map(m=>m.name));
 expect(actual.sources[1].pulse_length).toBeCloseTo(4e-15,27);
 const script=await page.request.post('/api/python',{data:actual});expect(await script.text()).toContain(actual.sources[1].name);
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.PHOTONWEAVE_TEST_CUDA?'cuda':'cpu');
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const job=await (await submitted).json();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 const result=await (await page.request.get('/api/jobs/'+job.id)).json();expect(result.status).toBe('completed');
 expect(result.flux_monitors.length).toBe(2);expect(result.flux_monitors.some(m=>m.flux.some(v=>Math.abs(v)>0))).toBe(true);
 if(process.env.PHOTONWEAVE_TEST_CUDA)expect(result.summary.gpu).toContain('5880');
 expect(errors).toEqual([]);
});
