import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';

test('duplicate, delete and add FSP primitives, export and run the resulting GPU scene',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const python=process.env.TORCHFDTD_TEST_PYTHON||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
 const raw=Buffer.from(execFileSync(python,['-c',"import sys,base64;sys.path.insert(0,'tests');from test_fsp_settings_write import settings_fixture;print(base64.b64encode(settings_fixture()).decode())"],{encoding:'utf8'}).trim(),'base64');
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="fsp-native"]').click();
 await page.locator('#fsp-native-input').setInputFiles({name:'authored-objects.fsp',mimeType:'application/octet-stream',buffer:raw});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();await expect(page.locator('#fsp-native-dialog')).not.toBeVisible();
 await expect(page.getByLabel('time steps',{exact:true})).toHaveValue('20');
 await page.getByLabel('time steps',{exact:true}).fill('70');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.locator('#tree .tree-row').filter({hasText:/^sphere$/}).click();
 await page.locator('[data-action="duplicate"]').click();
 await expect(page.locator('#tree')).toContainText('sphere_copy');
 await page.locator('#tree .tree-row').filter({hasText:/^sphere$/}).click();
 await page.locator('[data-action="delete"]').click();
 await expect(page.locator('#tree .tree-row').filter({hasText:/^sphere$/})).toHaveCount(0);
 await page.locator('[data-add="rectangle"]').click();
 await page.getByLabel('x',{exact:true}).fill('-0.6');await page.getByLabel('x',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'Move earlier in tree',exact:true}).click();
 await expect(page.getByRole('button',{name:'Move earlier in tree',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Move later in tree',exact:true}).click();
 await expect(page.getByRole('button',{name:'Move later in tree',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Move earlier in tree',exact:true}).click();
 const expected=await page.evaluate(()=>JSON.parse(localStorage.getItem('torchfdtd.project.v1')));
 expect(expected.structures.map(s=>s.kind)).toEqual(['rectangle','sphere']);
 await page.locator('[data-action="fsp-native"]').click();await page.locator('[data-native="export"]').click();
 await expect(page.locator('#fsp-native-status')).toContainText('Scene export verified',{timeout:20000});
 await expect(page.locator('[data-native-structure-export]')).toContainText('2 added · 1 removed · 2 total');
 const event=page.waitForEvent('download');await page.locator('[data-native="edited"]').click();
 const bytes=fs.readFileSync(await (await event).path());expect(bytes.equals(raw)).toBe(false);
 const reportEvent=page.waitForEvent('download');await page.locator('[data-native="write-report"]').click();
 const report=JSON.parse(fs.readFileSync(await (await reportEvent).path(),'utf8'));
 expect(report.structure_list.added).toHaveLength(2);expect(report.preserved_segments.length).toBeGreaterThan(2);
 await page.screenshot({path:'results/ui-fsp-objects-export.png',fullPage:true});
 await page.locator('#fsp-native-input').setInputFiles({name:'edited-objects.fsp',mimeType:'application/octet-stream',buffer:bytes});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await page.locator('[data-native="load"]').click();await expect(page.locator('#fsp-native-dialog')).not.toBeVisible();
 const actual=await page.evaluate(()=>JSON.parse(localStorage.getItem('torchfdtd.project.v1')));
 expect(actual.structures.map(s=>s.kind)).toEqual(['rectangle','sphere']);
 expect(actual.structures.map(s=>s.id)).toEqual(expected.structures.map(s=>report.id_mapping[s.id]));
 expect(actual.sources[0].id).toBe(report.id_mapping[expected.sources[0].id]);
 expect(actual.monitors[0].id).toBe(report.id_mapping[expected.monitors[0].id]);
 const script=await page.request.post('/api/python',{data:actual});expect(await script.text()).toContain('sphere_copy');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const job=await (await submitted).json();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 const result=await (await page.request.get('/api/jobs/'+job.id)).json();expect(result.status).toBe('completed');
 expect(result.flux_monitors[0].flux.some(v=>Math.abs(v)>0)).toBe(true);
 if(process.env.TORCHFDTD_TEST_CUDA)expect(result.summary.gpu).toContain('5880');
 expect(errors).toEqual([]);
});
