import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';

test('measured samples, failed tolerance, fit preview, persistence and native GPU execution',async({page})=>{
 test.setTimeout(120000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const python=process.env.TORCHFDTD_TEST_PYTHON||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
 const csv=execFileSync(python,['-c',"import sys,numpy as np;sys.path.insert(0,'tests');from test_material_fit import authored_data;d,_=authored_data();n=np.sqrt(d.epsilon);print('wavelength_nm,n,k');print('\\n'.join(f'{w*1000},{a},{b}' for w,a,b in zip(d.wavelength_um,n.real,n.imag)))"],{encoding:'utf8'});
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 const initial=await (await page.request.get('/api/examples/waveguide')).json();
 await page.evaluate(p=>{p.region.time_step_override=5e-17;p.region.steps=120;p.region.mesh_steps=[.04,.06,.04];p.region.material_sampling='yee';localStorage.setItem('torchfdtd.project.v1',JSON.stringify(p));},initial);
 await page.reload();await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="materials"]').click();const dialog=page.locator('.material-dialog');
 await dialog.getByRole('button',{name:'+ Add material',exact:true}).click();
 await dialog.getByLabel('Material name',{exact:true}).fill('Measured test');await dialog.getByLabel('Material name',{exact:true}).press('Tab');
 await dialog.locator('.material-fit summary').click();
 await dialog.getByLabel('Optical wavelength unit',{exact:true}).selectOption('nm');
 await dialog.getByLabel('Optical data file',{exact:true}).setInputFiles({name:'authored-response.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await expect(dialog.getByLabel('Optical data table',{exact:true})).toHaveValue(/wavelength_nm/);
 await dialog.getByRole('button',{name:'Import data',exact:true}).click();
 await expect(dialog.locator('[data-data-status]')).toContainText('121 samples');
 await dialog.getByLabel('Maximum fit poles',{exact:true}).fill('1');
 await dialog.getByLabel('Fit tolerance',{exact:true}).fill('0.000001');
 await dialog.getByRole('button',{name:'Fit optical data',exact:true}).click();
 await expect(dialog.locator('.fit-status')).toContainText('Tolerance NOT met');
 await expect(dialog.getByRole('button',{name:'Use fitted material',exact:true})).toBeDisabled();
 await expect(dialog.getByLabel('Material model',{exact:true})).toHaveValue('dielectric');
 await dialog.getByLabel('Maximum fit poles',{exact:true}).fill('3');
 await dialog.getByRole('button',{name:'Fit optical data',exact:true}).click();
 await expect(dialog.locator('.fit-status')).toContainText('Tolerance met',{timeout:30000});
 await expect(dialog.locator('.fit-status')).toContainText('3 poles');
 await expect(dialog.locator('.fit-status')).toContainText('0.050000 fs');
 await dialog.getByLabel('Measured and fitted optical response',{exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'results/ui-material-fit.png',fullPage:true});
 await dialog.getByRole('button',{name:'Use fitted material',exact:true}).click();
 await expect(dialog.getByLabel('Material model',{exact:true})).toHaveValue('multipole');
 await expect(dialog.locator('.material-status')).toContainText('Retained samples');
 await expect(dialog.locator('.material-status')).toContainText('0.050000 fs');
 await dialog.getByRole('button',{name:'Apply materials',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await page.locator('#tree .tree-row').nth(1).click();await page.getByLabel('material',{exact:true}).selectOption('Measured test');
 const saved=page.waitForEvent('download');await page.locator('[data-action="save"]').click();
 const project=JSON.parse(fs.readFileSync(await (await saved).path(),'utf8'));
 const material=project.materials.find(m=>m.name==='Measured test');
 expect(material.samples.wavelength_um).toHaveLength(121);expect(material.poles).toHaveLength(3);
 expect(material.samples.reference).toBe('authored-response.csv');
 expect(material.fit_band_um[0]).toBeCloseTo(.7,14);expect(material.fit_band_um[1]).toBeCloseTo(2.2,14);
 const script=await page.request.post('/api/python',{data:project});expect(await script.text()).toContain('authored-response.csv');
 await page.reload();await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-select="fdtd"]').click();
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.locator('#run-button').click();await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:60000});
 expect(errors).toEqual([]);
});

test('editing fit inputs discards an outstanding result',async({page})=>{
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="materials"]').click();const dialog=page.locator('.material-dialog');
 await dialog.locator('.material-fit summary').click();
 await dialog.getByLabel('Optical data table',{exact:true}).fill('1,1.5,0\n1.5,1.5,0\n2,1.5,0');
 await dialog.getByRole('button',{name:'Import data',exact:true}).click();await expect(dialog.locator('[data-data-status]')).toContainText('3 samples');
 let release,entered;const pending=new Promise(resolve=>release=resolve),started=new Promise(resolve=>entered=resolve);
 await page.route('**/api/materials/fit',async route=>{entered();await pending;await route.continue();});
 await dialog.getByRole('button',{name:'Fit optical data',exact:true}).click();await started;
 await dialog.getByLabel('Fit tolerance',{exact:true}).fill('0.002');
 const response=page.waitForResponse('**/api/materials/fit');release();await response;
 await expect(dialog.getByRole('button',{name:'Use fitted material',exact:true})).toBeDisabled();
 await expect(dialog.locator('.fit-status')).toContainText('Inputs changed');
});
