import {test,expect} from '@playwright/test';

test('select graded mesh, inspect nodes, edit and freeze refinements, run GPU',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-example="3d"]').click();
 await expect(page.getByLabel('dimension',{exact:true})).toHaveValue('3d');
 await page.getByLabel('mesh type',{exact:true}).selectOption('graded');
 await expect(page.getByLabel('interface sampling',{exact:true})).toHaveValue('yee');
 await page.getByLabel('fine mesh step',{exact:true}).fill('0.025');await page.getByLabel('fine mesh step',{exact:true}).press('Tab');
 await page.getByLabel('background cells / λ',{exact:true}).fill('16');await page.getByLabel('background cells / λ',{exact:true}).press('Tab');
 const response=page.waitForResponse(r=>r.url().endsWith('/api/mesh/preview'));
 await page.getByRole('button',{name:'Preview simulation mesh',exact:true}).click();
 expect((await (await response).json()).summary.cell_reduction_percent).toBeGreaterThan(30);
 const modal=page.locator('.mesh-dialog');await expect(modal).toBeVisible();
 await expect(modal).toContainText('fewer cells than uniform');
 await modal.getByLabel('Mesh projection').selectOption('xz');
 await page.screenshot({path:'results/ui-mesh-preview.png',fullPage:true});
 await modal.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'+ Add refinement region',exact:true}).click();
 await page.locator('#properties summary').filter({hasText:'Refinement 1'}).click();
 await page.locator('[data-path="mesh_refinements.0.size.0"]').fill('1.2');await page.locator('[data-path="mesh_refinements.0.size.0"]').press('Tab');
 await page.getByRole('button',{name:'Freeze automatic refinements',exact:true}).click();
 await expect(page.locator('[data-path="mesh_auto_refine"]')).not.toBeChecked();
 await page.locator('#properties summary').filter({hasText:'Refinement 1'}).click();
 await page.getByRole('button',{name:'Remove refinement',exact:true}).first().click();
 await page.getByLabel('time steps',{exact:true}).fill('150');await page.getByLabel('time steps',{exact:true}).press('Tab');
 const backend=process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu';await page.getByLabel('resource',{exact:true}).selectOption(backend);
 await page.locator('#run-button').click();await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 await expect(page.locator('.run-summary')).toContainText(backend==='cuda'?'CUDA graph':'CPU');
 const job=await page.evaluate(()=>localStorage.getItem('torchfdtd.project.v1'));
 expect(JSON.parse(job).region.mesh_type).toBe('graded');
 await page.locator('#layout-button').click();
 await page.getByLabel('mesh type',{exact:true}).selectOption('uniform');
 await expect(page.getByLabel('interface sampling',{exact:true})).toHaveValue('yee');
 expect(errors).toEqual([]);
});
