import fs from 'node:fs';
import { test, expect } from '@playwright/test';

test('PEC and anti-symmetric faces remain independent through export and execution',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.getByLabel('x min bc',{exact:true}).selectOption('pec');
 await expect(page.getByLabel('x max bc',{exact:true})).toHaveValue('pml');
 await page.getByLabel('x max bc',{exact:true}).selectOption('antisymmetric');
 await expect(page.getByLabel('x min bc',{exact:true})).toHaveValue('pec');
 await expect(page.getByLabel('x min bc',{exact:true}).locator('option[value="pmc"]')).toHaveCount(0);
 await page.getByLabel('time steps',{exact:true}).fill('100');
 await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 const download=page.waitForEvent('download');await page.locator('[data-action="save"]').click();
 const project=JSON.parse(fs.readFileSync(await (await download).path(),'utf8'));
 expect(project.region.boundaries.x_min.kind).toBe('pec');
 expect(project.region.boundaries.x_max.kind).toBe('antisymmetric');
 const exported=await page.request.post('/api/python',{data:project});
 expect(exported.ok()).toBe(true);expect(await exported.text()).toContain("'kind': 'antisymmetric'");
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const key=(await (await submitted).json()).id;
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:45000});
 const job=await (await page.request.get('/api/jobs/'+key)).json();
 expect(job.status).toBe('completed');
 expect(job.summary.boundaries.x_min.kind).toBe('pec');
 expect(job.summary.boundaries.x_max.kind).toBe('antisymmetric');
 expect(job.monitors.some(m=>m.signal.some(v=>v!==0))).toBe(true);
 expect(errors).toEqual([]);
});
