import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';

test('closed PMC scene edits atomically, runs, exports Python and saves endpoint fields',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-example="pmc"]').click();
 await expect(page.getByLabel('x min bc',{exact:true})).toHaveValue('pmc');
 await page.getByLabel('resource',{exact:true}).selectOption('cpu');
 await page.getByRole('button',{name:'Edit six faces together',exact:true}).click();
 const modal=page.locator('.boundary-dialog');await expect(modal).toBeVisible();
 await modal.getByLabel('x min boundary',{exact:true}).selectOption('pec');
 await modal.getByLabel('y min boundary',{exact:true}).selectOption('symmetric');
 await modal.getByRole('button',{name:'Apply boundaries',exact:true}).click();
 await expect(modal).not.toBeVisible();
 await expect(page.getByLabel('x min bc',{exact:true})).toHaveValue('pec');
 await expect(page.getByLabel('y min bc',{exact:true})).toHaveValue('symmetric');
 const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('torchfdtd.project.v1')));
 const download=page.waitForEvent('download');await page.locator('[data-action="export-python"]').click();
 const script=await readFile(await (await download).path(),'utf8');
 expect(script).toContain('pmc');expect(script).toContain('symmetric');expect(script).toContain('Simulation');
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const id=(await (await submitted).json()).id;
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 await expect(page.locator('#status-text')).toHaveText('completed');
 const job=await (await page.request.get('/api/jobs/'+id)).json();
 expect(job.summary.steps).toBe(saved.region.steps);
 expect(job.summary.backend).toBe('cpu');
 expect(job.monitors.length).toBe(saved.monitors.length);
 expect(job.monitors.some(m=>m.signal.some(x=>Math.abs(x)>1e-12))).toBeTruthy();
 const fields=await (await page.request.get('/api/jobs/'+id+'/fields')).json();
 expect(fields.frames.length).toBeGreaterThan(1);
 expect(fields.frames.flat(2).every(Number.isFinite)).toBeTruthy();
 const npz=await page.request.get('/api/jobs/'+id+'/download');expect(npz.ok()).toBeTruthy();
 expect((await npz.body()).length).toBeGreaterThan(100);
 await page.screenshot({path:'results/ui-pmc-cavity.png',fullPage:true});
 await page.locator('#layout-button').click();
 await page.getByRole('button',{name:'Edit six faces together',exact:true}).click();
 await modal.getByLabel('x min boundary',{exact:true}).selectOption('pml');
 await modal.getByRole('button',{name:'Apply boundaries',exact:true}).click();
 await expect(modal.locator('[data-boundary-status]')).toContainText(/closed|pmc/i);
 await expect(modal).toBeVisible();
 const after=JSON.parse(await page.evaluate(()=>localStorage.getItem('torchfdtd.project.v1')));
 expect(after.region.boundaries).toEqual(saved.region.boundaries);
 await modal.getByRole('button',{name:'Cancel',exact:true}).click();
 expect(errors).toEqual([]);
});
