import {test,expect} from '@playwright/test';
import fs from 'node:fs';

test('priorities filter, decay controls, completion reason and Python export',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const project={name:'Decay verification',region:{size:[4,4,1],mesh:.1,pml_cells:5,steps:1400,snapshot_interval:500,backend:process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu'},structures:[],sources:[{kind:'point',center:[0,0,0],wavelength:1,pulse_cycles:1}],monitors:[{center:[.8,0,0]}]};
 await page.addInitScript(p=>localStorage.setItem('torchfdtd.project.v1',JSON.stringify(p)),project);
 await page.goto('/');await expect(page.locator('#tree')).toContainText('FDTD');
 await page.locator('[data-action="capabilities"]').click();
 const audit=page.locator('.capability-dialog');
 await audit.getByLabel('Capability priority',{exact:true}).selectOption('P0');
 await audit.getByLabel('Search capabilities').fill('auto shutoff');
 await expect(audit.locator('tbody')).toContainText('구현');
 await audit.getByLabel('Search capabilities').fill('');
 await audit.getByLabel('Capability priority',{exact:true}).selectOption('P3');
 await expect(audit.locator('tbody')).toContainText('목표에서 제외');
 await audit.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByLabel('Automatic decay shutoff',{exact:true}).check();
 await page.getByLabel('decay threshold',{exact:true}).fill('0.00001');await page.getByLabel('decay threshold',{exact:true}).press('Tab');
 await page.getByLabel('check every',{exact:true}).fill('25');await page.getByLabel('check every',{exact:true}).press('Tab');
 await page.locator('#run-button').click();
 await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:60000});
 await expect(page.locator('.run-summary')).toContainText('Decay threshold reached');
 await expect(page.locator('.run-summary')).toContainText('/ 1400 steps');
 const download=page.waitForEvent('download');await page.locator('[data-action="export-python"]').click();
 const python=fs.readFileSync(await (await download).path(),'utf8');
 expect(python).toContain("'auto_shutoff': True");
 expect(python).toContain("'check_interval': 25");
 await page.screenshot({path:'results/ui-priority-decay.png',fullPage:true});
 expect(errors).toEqual([]);
});

test('edit several passive poles, preview and persist the complete material',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="materials"]').click();
 const dialog=page.locator('.material-dialog');
 await dialog.getByRole('button',{name:'+ Add material',exact:true}).click();
 await dialog.getByLabel('Material model',{exact:true}).selectOption('multipole');
 await dialog.getByRole('button',{name:'+ Add pole',exact:true}).click();
 await dialog.getByLabel('Pole 1 Resonance',{exact:true}).fill('0');await dialog.getByLabel('Pole 1 Resonance',{exact:true}).press('Tab');
 await dialog.getByLabel('Pole 2 Damping',{exact:true}).fill('200000000000000');await dialog.getByLabel('Pole 2 Damping',{exact:true}).press('Tab');
 await dialog.getByRole('button',{name:'Plot n / k',exact:true}).click();
 await expect(dialog.locator('.material-status')).toContainText('301 wavelengths');
 await page.screenshot({path:'results/ui-multipole.png',fullPage:true});
 await dialog.getByRole('button',{name:'Apply materials',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 const download=page.waitForEvent('download');await page.locator('[data-action="save"]').click();
 const saved=JSON.parse(fs.readFileSync(await (await download).path(),'utf8'));
 const m=saved.materials.find(v=>v.model==='multipole');
 expect(m.poles).toHaveLength(2);expect(m.poles[0].resonance_rad_s).toBe(0);expect(m.poles[1].damping_rad_s).toBe(2e14);
 expect(errors).toEqual([]);
});
