import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';

test('axis spacing, atomic explicit nodes, Python export and native solve',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-example="3d"]').click();
 await expect(page.getByLabel('dimension',{exact:true})).toHaveValue('3d');
 await page.getByLabel('Independent axis spacing',{exact:true}).check();
 await page.getByLabel('dy',{exact:true}).fill('0.08');await page.getByLabel('dy',{exact:true}).press('Tab');
 await expect(page.getByLabel('interface sampling',{exact:true})).toHaveValue('yee');
 await page.getByLabel('time steps',{exact:true}).fill('80');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.getByRole('button',{name:'Edit explicit node arrays',exact:true}).click();
 const dialog=page.locator('.mesh-dialog');await expect(dialog).toBeVisible();
 const x=dialog.getByLabel('x mesh nodes',{exact:true}),original=await x.inputValue();
 await x.fill('0, 0, 1');await dialog.getByRole('button',{name:'Apply node arrays',exact:true}).click();
 await expect(dialog.locator('[role="alert"]')).not.toBeEmpty();
 await x.fill(original);await dialog.getByRole('button',{name:'Apply node arrays',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByLabel('mesh type',{exact:true})).toHaveValue('explicit');
 const project=await page.evaluate(()=>JSON.parse(localStorage.getItem('torchfdtd.project.v1')));
 expect(project.region.mesh_coordinates).toHaveLength(3);
 const response=await page.request.post('/api/python',{data:project});expect(await response.text()).toContain('mesh_coordinates');
 await page.getByRole('button',{name:'Preview simulation mesh',exact:true}).click();
 await expect(dialog).toContainText('actual cell boundaries');
 await page.screenshot({path:'results/ui-rectilinear-mesh.png',fullPage:true});
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('#run-button').click();await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 expect(errors).toEqual([]);
});

test('synthetic nonuniform FSP retains nodes and original bytes through GPU workflow',async({page})=>{
 const python=process.env.TORCHFDTD_TEST_PYTHON||(process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
 const encoded=execFileSync(python,['-c',"import sys,base64;sys.path.insert(0,'tests');from test_fsp_native import fixture;from test_fsp_mesh import settings;print(base64.b64encode(fixture(region_overrides=settings())).decode())"],{encoding:'utf8'}).trim();
 const raw=Buffer.from(encoded,'base64');
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-action="fsp-native"]').click();
 await page.locator('#fsp-native-input').setInputFiles({name:'synthetic-nonuniform.fsp',mimeType:'application/octet-stream',buffer:raw});
 await expect(page.locator('#fsp-native-status')).toContainText('Ready to open',{timeout:20000});
 await expect(page.locator('.native-issues')).toContainText('frozen mesh');
 const downloaded=page.waitForEvent('download');await page.locator('[data-native="original"]').click();
 expect(fs.readFileSync(await (await downloaded).path())).toEqual(raw);
 await page.locator('[data-native="load"]').click();
 await expect(page.getByLabel('mesh type',{exact:true})).toHaveValue('explicit');
 const p=await page.evaluate(()=>JSON.parse(localStorage.getItem('torchfdtd.project.v1')));
 expect(p.region.mesh_coordinates.map(v=>v.length)).toEqual([49,49,49]);
 expect(p.region.time_step_override).toBeGreaterThan(0);
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.locator('#run-button').click();await expect(page.locator('#mode-badge')).toHaveText('ANALYSIS',{timeout:90000});
 await page.screenshot({path:'results/ui-rectilinear-fsp.png',fullPage:true});
});
