import { test, expect } from '@playwright/test';

test('edit global pulse and custom signal, inspect injection, run CUDA and retain overrides',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.getByLabel('time steps',{exact:true}).fill('600');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.TORCHFDTD_TEST_CUDA?'cuda':'cpu');
 await page.locator('[data-select="source"]').click();
 await page.getByLabel('wavelength',{exact:true}).fill('1.6');await page.getByLabel('wavelength',{exact:true}).press('Tab');
 await page.getByLabel('phase',{exact:true}).fill('37');await page.getByLabel('phase',{exact:true}).press('Tab');
 await page.getByLabel('amplitude',{exact:true}).fill('0.7');await page.getByLabel('amplitude',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'Edit global source settings',exact:true}).click();
 const dialog=page.locator('.source-dialog');
 await page.getByLabel('global wavelength (µm)',{exact:true}).fill('1.45');
 await page.getByLabel('global time definition',{exact:true}).selectOption('standard');
 await page.getByLabel('global pulselength (fs)',{exact:true}).fill('23');
 await page.getByLabel('global offset (fs)',{exact:true}).fill('67');
 await page.getByRole('button',{name:'Apply global settings',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await page.getByLabel('Use global source settings',{exact:true}).check();
 await expect(page.getByLabel('wavelength',{exact:true})).toHaveValue('1.45');
 await expect(page.getByLabel('wavelength',{exact:true})).toBeDisabled();
 await expect(page.getByLabel('phase',{exact:true})).toHaveValue('37');
 await page.getByLabel('Use global source settings',{exact:true}).uncheck();
 await expect(page.getByLabel('wavelength',{exact:true})).toHaveValue('1.6');
 await page.getByRole('button',{name:'Load / edit time signal',exact:true}).click();
 await page.getByLabel('Time signal file',{exact:true}).setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('time_s,amplitude,phase_rad\n0,0,0\n0,1,2')});
 await expect(dialog.getByRole('alert')).toContainText('strictly increasing');
 await expect(dialog.getByRole('button',{name:'Apply time signal',exact:true})).toBeDisabled();
 const csv='time_s,amplitude,phase_rad\n0,0,0\n1e-14,1,-12\n4e-14,0.5,-48\n6e-14,0,-72';
 await page.getByLabel('Time signal file',{exact:true}).setInputFiles({name:'pulse.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await expect(dialog.locator('.signal-summary')).toContainText('4 samples');
 await page.getByRole('button',{name:'Apply time signal',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByLabel('pulse',{exact:true})).toHaveValue('sampled');
 await page.getByRole('button',{name:'Preview time signal / spectrum',exact:true}).click();
 await expect(dialog).toContainText('600 samples');
 await page.screenshot({path:'results/ui-source-time.png',fullPage:true});
 await dialog.getByRole('button',{name:'Spectrum',exact:true}).click();
 await page.getByLabel('Source spectrum axis',{exact:true}).selectOption('wavelength');
 await page.screenshot({path:'results/ui-source-spectrum.png',fullPage:true});
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const key=(await (await submitted).json()).id;
 await expect(page.locator('#results-tree')).toContainText('field snapshots',{timeout:45000});
 const job=await (await page.request.get('/api/jobs/'+key)).json();
 expect(job.project.sources[0].signal.phase_rad).toEqual([0,-12,-48,-72]);
 expect(job.project.sources[0].phase).toBe(37);expect(job.project.sources[0].amplitude).toBe(.7);
 expect(job.monitors[0].signal.some(v=>Math.abs(v)>1e-4)).toBe(true);
 if(process.env.TORCHFDTD_TEST_CUDA)expect(job.summary.cuda_graph).toBe(true);
 await expect(page.getByRole('button',{name:'Edit global source settings',exact:true})).toBeDisabled();
 await page.reload();await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-select="source"]').click();
 await expect(page.getByLabel('pulse',{exact:true})).toHaveValue('sampled');
 expect(errors).toEqual([]);
});
