import { test, expect } from '@playwright/test';

test('set wavelength samples and apodization, run CUDA, export complex spectra',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('#tree')).toContainText('waveguide');
 await page.getByLabel('time steps',{exact:true}).fill('600');await page.getByLabel('time steps',{exact:true}).press('Tab');
 await page.getByLabel('resource',{exact:true}).selectOption(process.env.PHOTONWEAVE_TEST_CUDA?'cuda':'cpu');
 await page.locator('[data-select="output"]').click();
 await page.getByLabel('sample spacing',{exact:true}).selectOption('wavelength');
 await expect(page.getByLabel('apodization',{exact:true})).toHaveValue('none');
 await page.getByLabel('minimum wavelength',{exact:true}).fill('1.4');await page.getByLabel('minimum wavelength',{exact:true}).press('Tab');
 await page.getByLabel('maximum wavelength',{exact:true}).fill('1.7');await page.getByLabel('maximum wavelength',{exact:true}).press('Tab');
 await page.getByLabel('frequency points',{exact:true}).fill('61');await page.getByLabel('frequency points',{exact:true}).press('Tab');
 await page.getByLabel('apodization',{exact:true}).selectOption('full');
 await page.getByLabel('apodization center',{exact:true}).fill('40');await page.getByLabel('apodization center',{exact:true}).press('Tab');
 await page.getByLabel('apodization time width',{exact:true}).fill('25');await page.getByLabel('apodization time width',{exact:true}).press('Tab');
 await expect(page.getByLabel('apodization center',{exact:true})).toHaveValue('40');
 await page.getByLabel('apodization time width',{exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'results/ui-apodization-settings.png',fullPage:true});
 const submitted=page.waitForResponse(r=>r.url().endsWith('/api/jobs')&&r.request().method()==='POST');
 await page.locator('#run-button').click();const key=(await (await submitted).json()).id;
 await expect(page.locator('#results-tree')).toContainText('field snapshots',{timeout:45000});
 const job=await (await page.request.get('/api/jobs/'+key)).json();
 const m=job.monitors.find(m=>m.id==='output');
 expect(m.spectrum_settings.apodization_center).toBeCloseTo(40e-15,25);
 expect(m.spectrum).toHaveLength(61);
 expect(m.wavelength_um[0]).toBeCloseTo(1.4,12);
 expect(m.wavelength_um.at(-1)).toBeCloseTo(1.7,12);
 expect(m.spectrum.some(x=>x>0)).toBe(true);
 if(process.env.PHOTONWEAVE_TEST_CUDA)expect(job.summary.cuda_graph).toBe(true);
 await page.getByLabel('Plot monitor',{exact:true}).selectOption('output');
 await page.locator('[data-plot="spectrum"]').click();
 await page.getByLabel('Spectrum axis',{exact:true}).selectOption('wavelength');
 const csv=await (await page.request.get('/api/jobs/'+key+'/spectra.csv')).text();
 expect(csv).toContain('wavelength_um,real,imag,magnitude,units,apodization');
 expect(csv).toContain('reduced field * s,full');
 await page.screenshot({path:'results/ui-apodization-spectrum.png',fullPage:true});
 await page.reload();await expect(page.locator('#tree')).toContainText('waveguide');
 await page.locator('[data-select="output"]').click();
 await expect(page.getByLabel('apodization center',{exact:true})).toHaveValue('40');
 expect(errors).toEqual([]);
});
