"""Figures and tables used only by the Computer Physics Communications version (docs/paper-cpc).

Everything is read from validation records, and no solver runs. The shared figure style and the panel functions
come from scripts/build_paper_story_figures.py. Outputs go to docs/paper-cpc/figures and docs/paper-cpc/tables,
and docs/paper-cpc/cpc-asset-provenance.json lists the SHA-256 of every record read.
"""
from __future__ import annotations

import hashlib
import json
import statistics
from pathlib import Path

import numpy as np

import build_paper_story_figures as sty
from build_paper_story_figures import plt, panel, BLUE, TEAL, ORANGE, GREY, INK, MUTED, LINE, WIDTH

ROOT = Path(__file__).resolve().parents[1]
CPC = ROOT / 'docs/paper-cpc'
TABLES = CPC / 'tables'


def table(name: str, caption: str, label: str, spec: str, header: list[str], rows: list[list[str]], note: str = '') -> None:
    TABLES.mkdir(parents=True, exist_ok=True)
    lines = ['% Generated by scripts/build_cpc_assets.py from validation records.',
             '\\begin{table}[tbp]', '\\centering', '\\small', '\\renewcommand{\\arraystretch}{1.15}',
             f'\\caption{{{caption}}}', f'\\label{{{label}}}', f'\\begin{{tabular}}{{{spec}}}', '\\toprule',
             ' & '.join(header) + ' \\\\', '\\midrule']
    lines += [' & '.join(r) + ' \\\\' for r in rows]
    lines += ['\\bottomrule', '\\end{tabular}']
    if note:
        lines.append(note)
    lines.append('\\end{table}')
    (TABLES / f'{name}.tex').write_bytes(('\n'.join(lines) + '\n').encode('utf-8'))


def median_peak(record: dict, mode: str, key: str = 'peak_torch_cuda_allocated_bytes') -> float:
    return statistics.median(r[key] for r in record['records'][mode]) / 1e9


# ---------------------------------------------------------------- tables
def scaling_tables() -> None:
    fwd = sty.read('paper_review/scaling-forward-3060.json')
    sfwd = sty.read('paper_review/scaling-forward-streamed-3060.json')
    rows = []
    for c in fwd['cases']:
        if 'median' not in c:
            continue
        rows.append([f"${c['n']}^3$", f"{c['cells'] / 1e6:.1f}", 'resident',
                     f"{c['cell_steps_per_second_loop'] / 1e9:.2f}",
                     f"{c['cells'] * fwd['steps'] / c['median']['wall_seconds'] / 1e9:.2f}",
                     f"{c['median']['peak_allocated_bytes'] / 1e9:.3f}"])
    for c in sfwd['cases']:
        if 'median' not in c:
            continue
        rows.append([f"${c['n']}^3$", f"{c['cells'] / 1e6:.1f}", f"streamed, $W={c['slab_width']}$", '',
                     f"{c['cell_steps_per_second_full'] / 1e9:.2f}", f"{c['median']['peak_allocated_bytes'] / 1e9:.3f}"])
    table('si-scaling-forward',
          f"Forward solves over grid size on the RTX 3060 with {fwd['steps']} steps, medians of three warmed runs. "
          'The resident rows are the dielectric sphere of Section 7.3, and the streamed rows the periodic slab with two '
          'point monitors and a uniform permittivity. Rates are in $10^9$ cell-steps per second, and the stepping rate '
          'counts the time-stepping loop alone. Peak device allocation is in GB.',
          'tab:si-scaling-forward', '@{}rrlrrr@{}',
          ['Grid', 'Cells ($10^6$)', 'Path', 'Stepping', 'Full solve', 'Peak (GB)'], rows)

    rows = []
    for n in (128, 192, 256, 320, 384):
        r = sty.read(f'paper_review/scaling-adjoint-3060-{n}.json')
        res = r['records'].get('cuda_resident')
        dram = r['records']['cuda_dram']
        rs = r['median_seconds']
        rows.append([f'${n}^3$',
                     f"{rs['cuda_resident']:.2f}" if res else 'above budget',
                     f"{median_peak(r, 'cuda_resident'):.2f}" if res else '',
                     f"{rs['cuda_dram']:.2f}", f"{median_peak(r, 'cuda_dram'):.2f}",
                     f"{median_peak(r, 'cuda_dram', 'sampled_peak_process_rss_bytes'):.1f}",
                     str(r['configuration']['slab_width']),
                     f"{rs['cuda_dram'] / rs['cuda_resident']:.1f}" if res else ''])
    table('si-scaling-adjoint',
          'Time to gradient of the dielectric adjoint fixture over grid size on the RTX 3060, 128 steps, two '
          'checkpoints, temporal depth 8 and four host threads, medians of three warmed repetitions. Device peaks and '
          'the sampled host memory of the streamed process are in GB, and the last column is the ratio of streamed to '
          'resident time. At $384^3$ only the streamed adjoint fits the 10 GiB device budget.',
          'tab:si-scaling-adjoint', '@{}rrrrrrrr@{}',
          ['Grid', '\\shortstack{Resident\\\\(s)}', '\\shortstack{Resident\\\\peak}', '\\shortstack{Streamed\\\\(s)}',
           '\\shortstack{Streamed\\\\peak}', '\\shortstack{Host\\\\memory}', '$W$', 'Ratio'], rows)


def host_table() -> None:
    rows = []
    sources = [('A100 80GB PCIe, container with 4 cores', 'cpu-gpu-adjoint-256-{}-a100.json', ('dielectric', 'ade')),
               ('RTX 5880 Ada, workstation with 8 physical cores', 'cpu-gpu-adjoint-256-{}-5880.json', ('dielectric', 'ade')),
               ('RTX 3060, workstation with an i7-12700', 'paper_review/scaling-adjoint-3060-256.json', ('dielectric',))]
    for host, pattern, cases in sources:
        for case in cases:
            r = sty.read(pattern.format(case) if '{}' in pattern else pattern)
            cfg = r['configuration']
            assert cfg['size'] == 256 and cfg['steps'] == 128 and cfg['checkpoints'] == 2 and cfg['slab_width'] == 32
            assert cfg['temporal_depth'] == 8 and cfg['gpu_host_threads'] == 4 and cfg['dispersive'] == (case == 'ade')
            rs = r['median_seconds']
            rows.append([host, 'two-pole' if case == 'ade' else 'dielectric', f"{rs['cuda_resident']:.2f}",
                         f"{rs['cuda_dram']:.2f}", f"{rs['cuda_dram'] / rs['cuda_resident']:.1f}"])
            host = ''
    table('si-host',
          'Resident and host-streamed adjoints of the matched $256^3$ fixtures of Section 7.2 on three hosts, 128 steps, '
          'two checkpoints, slab width 32, temporal depth 8 and four host threads, medians of three warmed repetitions.',
          'tab:si-host', '@{}llrrr@{}', ['Host', 'Case', 'Resident (s)', 'Streamed (s)', 'Ratio'], rows)


def microring_table() -> None:
    c = sty.read('meep_comparison/microring_comparison.json')
    fits = {solver: [r for r in c['resonances'][solver] if isinstance(r, dict) and r.get('valid')]
            for solver in ('torchfdtd', 'meep')}
    assert len(fits['torchfdtd']) == len(fits['meep'])
    rows = []
    for a, b in zip(fits['torchfdtd'], fits['meep']):
        rows.append([f"{a['center_nm']:.4f}", f"{abs(a['center_nm'] - b['center_nm']):.1e}",
                     f"{a['q_loaded']:.1f}", f"{b['q_loaded']:.1f}", f"{a['extinction_db']:.3f}", f"{b['extinction_db']:.3f}"])
    table('si-microring',
          'Lorentzian fits of the four resonances of the microring of Section 6.3 from TorchFDTD and Meep on one grid. '
          'The loaded quality factors describe the spectra of the 5 ps window.',
          'tab:si-microring', '@{}rrrrrr@{}',
          ['\\shortstack{Resonance\\\\(nm)}', '\\shortstack{$|\\Delta\\lambda|$\\\\(nm)}', '\\shortstack{$Q$\\\\TorchFDTD}',
           '\\shortstack{$Q$\\\\Meep}', '\\shortstack{Extinction (dB)\\\\TorchFDTD}', '\\shortstack{Extinction (dB)\\\\Meep}'],
          rows)


def metalens_table() -> None:
    m = sty.read('meep_comparison/metalens_comparison.json')['3d']
    row = {r['name']: r for r in m['criteria_rows']}
    entries = [(1.55, {'focal_position_um': row['focal_position']['torchfdtd'], 'efficiency': row['efficiency']['torchfdtd'],
                       'fwhm_um': [row['fwhm_x']['torchfdtd'], row['fwhm_y']['torchfdtd']]},
                {'focal_position_um': row['focal_position']['meep'], 'efficiency': row['efficiency']['meep'],
                 'fwhm_um': [row['fwhm_x']['meep'], row['fwhm_y']['meep']]})]
    entries += [(e['wavelength_um'], e['torchfdtd'], e['meep']) for e in m['extra_wavelengths']]
    rows = []
    for wl, t, mp in sorted(entries, key=lambda e: e[0]):
        rows.append([f'{wl:.2f}', f"{t['focal_position_um']:.4f}", f"{mp['focal_position_um']:.4f}",
                     f"{t['fwhm_um'][0]:.4f}", f"{mp['fwhm_um'][0]:.4f}", f"{t['efficiency']:.5f}", f"{mp['efficiency']:.5f}"])
    table('si-metalens',
          'Focal position above the output plane, focal-plane full width at half maximum along $x$ and focusing '
          'efficiency of the pillar lens of Section 6.3 from TorchFDTD (T) and Meep (M) on one grid. Lengths are in '
          '\\micron{}.',
          'tab:si-metalens', '@{}rrrrrrr@{}',
          ['\\shortstack{Wavelength\\\\(\\micron{})}', 'Focus T', 'Focus M', 'FWHM T', 'FWHM M', 'Efficiency T',
           'Efficiency M'], rows)


def metagrating_table() -> None:
    r = sty.read('paper_review/metagrating_showcase.json')
    rows = []
    for seed, v in sorted(r['seed_selection']['per_seed'].items()):
        rows.append([seed, f"{v['last_efficiency']:.3f}", f"{v['coarse_smooth']:.3f}", f"{v['fine_gds']:.3f}",
                     f"{v['fine_gds_holdout']:.3f}"])
    table('si-metagrating-seeds',
          'The $+1$ efficiency of the three metagrating seeds of Section 8.1 at the design-run lengths, 800 steps on the '
          '50 nm mesh and 1600 steps on the 25 nm mesh. The last iteration and the smooth final density are evaluated '
          'on the design mesh at 1.00 \\micron{}, and the exported GDS layout on the 25 nm mesh at 1.00 and '
          '0.95 \\micron{}. Section 8.1 of the main text reports the final layout evaluated with runs four times longer.',
          'tab:si-metagrating-seeds', '@{}lrrrr@{}',
          ['Seed', 'Last iteration', 'Smooth final', 'GDS, 1.00 \\micron{}', 'GDS, 0.95 \\micron{}'], rows)


# ---------------------------------------------------------------- figures
def figures() -> None:
    sty.OUT = CPC / 'figures'
    p = sty.application_record()
    fig, ax = plt.subplots(figsize=(WIDTH * 0.56, 2.35))
    sty.application_check(ax, p)
    ax.set_title('End-to-end derivative check', loc='left', fontsize=8, pad=7, color=INK)
    fig.tight_layout()
    sty.save(fig, 'propagated-adjoint-check')

    fig, ax = plt.subplots(figsize=(WIDTH * 0.8, 1.7))
    sty.application_timeline(ax, p)
    ax.set_title('Streamed optical-objective evaluation', loc='left', fontsize=8, pad=7, color=INK)
    fig.tight_layout()
    sty.save(fig, 'propagated-adjoint-timeline')

    r = sty.read('paper_review/metagrating_showcase.json')
    s = r['spectra']
    wl = np.asarray(s['wavelength_um'])
    runs = [('fine', 'workflow_duration', 'final_binary', BLUE, (0, (3, 2)), 'final, 1600 steps'),
            ('fine', 'long_duration', 'final_binary', BLUE, '-', 'final, 6400 steps'),
            ('fine', 'long_duration', 'initial', GREY, '-', 'initial, 6400 steps')]
    fig, axes = plt.subplots(1, 2, figsize=(WIDTH, 2.35))
    ax = axes[0]
    for mesh, dur, design, color, ls, label in runs:
        e = s[mesh][dur][design]
        ax.plot(wl, np.abs(1 - np.asarray(e['T_total_plus_R'])), color=color, ls=ls, lw=1.1, label=label)
    ax.set(yscale='log', xlabel='Wavelength (µm)', ylabel='|1 $-$ (T + R)|', xlim=(wl.min(), wl.max()), ylim=(1e-8, 0.3))
    ax.legend(loc='lower left', fontsize=6.0)
    panel(ax, 'a', 'Energy balance, 25 nm mesh')
    ax = axes[1]
    for mesh, dur, design, color, ls, label in runs[:2]:
        ax.plot(wl, s[mesh][dur][design]['T_plus1'], color=color, ls=ls, lw=1.2, label=label)
    ax.axvline(1.0, color=LINE, lw=0.6, zorder=0)
    ax.set(xlabel='Wavelength (µm)', ylabel='+1 order efficiency', xlim=(wl.min(), wl.max()), ylim=(0, 0.7))
    ax.legend(loc='upper left', fontsize=6.0)
    panel(ax, 'b', 'Final layout')
    fig.tight_layout(w_pad=1.8)
    sty.save(fig, 'metagrating-convergence')


def main() -> None:
    sty.apply_style()
    sty.INPUTS.clear()
    scaling_tables()
    host_table()
    microring_table()
    metalens_table()
    metagrating_table()
    figures()
    provenance = {'generator': 'scripts/build_cpc_assets.py',
                  'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
                  'inputs': {f'docs/validation/{k}': v for k, v in sorted(sty.INPUTS.items())}}
    (CPC / 'cpc-asset-provenance.json').write_bytes((json.dumps(provenance, indent=2) + '\n').encode('utf-8'))


if __name__ == '__main__':
    main()
