"""Build the Computer Physics Communications submission: manuscript, Supplementary Material, highlights and sources.

The CPC version lives in docs/paper-cpc and is maintained separately from the arXiv version in docs/paper.
Figures and tables of the arXiv build are shared (docs/paper/figures, docs/paper/tables), and the figures and
tables used only here are generated by scripts/build_cpc_assets.py into docs/paper-cpc. Run scripts/build_paper.py
first when records change. No solver runs.

Checks against the CPC guide for authors: abstract at most 250 words, Program Summary fields of about 50 to 250
words, 1 to 7 keywords, 3 to 5 highlights of at most 85 characters, the required declarations, every Supplementary
Section cited by the main text present in the Supplementary Material, no overfull boxes and no unresolved references.
Supplementary Sections are numbered S1, S2, ... in the order of the Supplementary Material, and the main text reads
these numbers from si-numbers.tex, which this script writes from the labels si:<key>.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

ROOT = Path(__file__).resolve().parents[1]
CPC = ROOT / 'docs/paper-cpc'
SHARED = ROOT / 'docs/paper'
BUILD = ROOT / 'tmp/cpc'
OUT = ROOT / 'output/cpc'
MAIN, SUPP = 'manuscript-cpc', 'supplementary-cpc'


def words(text: str) -> int:
    text = re.sub(r'\\[a-zA-Z]+\*?(\[[^]]*\])?', ' ', text)
    text = re.sub(r'[{}$~]', ' ', text)
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9.,%'\-^/]*", text))


def check_front_matter(tex: str) -> dict:
    abstract = re.search(r'\\begin\{abstract\}(.+?)\\noindent \\textbf\{PROGRAM SUMMARY\}', tex, re.S).group(1)
    report = {'abstract_words': words(abstract)}
    if report['abstract_words'] > 250:
        raise ValueError(f"Abstract has {report['abstract_words']} words, CPC allows 250.")
    summary = re.search(r'\\textbf\{PROGRAM SUMMARY\}(.+?)\\end\{abstract\}', tex, re.S).group(1)
    for field in ('Nature of problem', 'Solution method', 'Additional comments including restrictions and unusual features'):
        m = re.search(re.escape('{\\em ' + field + ':}') + r'(.+?)(?=\{\\em |\\end\{small\})', summary, re.S)
        count = words(m.group(1))
        report[field] = count
        if not 50 <= count <= 250:
            raise ValueError(f'Program Summary field "{field}" has {count} words, CPC asks for about 50 to 250.')
    for required in ('Program Title', 'CPC Library link to program files', "Developer's repository link",
                     'Licensing provisions', 'Programming language'):
        if '{\\em ' + required not in summary:
            raise ValueError(f'Program Summary lacks "{required}".')
    keywords = re.search(r'\\begin\{keyword\}(.+?)\\end\{keyword\}', tex, re.S).group(1).split('\\sep')
    report['keywords'] = len(keywords)
    if not 1 <= len(keywords) <= 7:
        raise ValueError(f'{len(keywords)} keywords, CPC asks for 1 to 7.')
    for section in ('CRediT authorship contribution statement', 'Funding', 'Declaration of competing interest',
                    'Declaration of generative AI', 'Data availability'):
        if '\\section*{' + section not in tex:
            raise ValueError(f'Missing section "{section}".')
    return report


def check_highlights(path: Path) -> list[str]:
    lines = [line.strip() for line in path.read_text(encoding='utf-8').splitlines() if line.strip()]
    if not 3 <= len(lines) <= 5:
        raise ValueError(f'{len(lines)} highlights, CPC asks for 3 to 5.')
    for line in lines:
        if len(line) > 85:
            raise ValueError(f'Highlight longer than 85 characters ({len(line)}): {line}')
    return lines


def write_si_numbers(tex: str, si: str) -> dict[str, str]:
    """Number the Supplementary Sections from their labels and check every key the main text cites."""
    keys = re.findall(r'\\section\{[^}]+\}\n\\label\{si:([a-z]+)\}', si)
    if len(keys) != len(re.findall(r'\\section\{', si)):
        raise ValueError('Every Supplementary Section needs a \\label{si:<key>} on the line after \\section.')
    numbers = {key: f'S{i}' for i, key in enumerate(keys, 1)}
    cited = set(re.findall(r'\\suppsec\{([a-z]+)\}', tex))
    for pair in re.findall(r'\\suppsecs\{([a-z]+)\}\{([a-z]+)\}', tex):
        cited.update(pair)
    missing = sorted(cited - set(numbers))
    if missing:
        raise ValueError(f'The main text cites Supplementary Sections that do not exist: {missing}')
    uncited = sorted(set(numbers) - cited)
    lines = ['% Written by scripts/build_cpc.py from the labels of supplementary-cpc.tex. Do not edit.']
    lines += [f'\\expandafter\\def\\csname si@{key}\\endcsname{{{number}}}' for key, number in numbers.items()]
    (CPC / 'si-numbers.tex').write_bytes(('\n'.join(lines) + '\n').encode('utf-8'))
    if uncited:
        print('Supplementary Sections not cited by the main text:', uncited)
    return numbers


def run(command: list[str], name: str) -> None:
    result = subprocess.run(command, cwd=BUILD, capture_output=True, text=True, encoding='utf-8', errors='replace')
    (BUILD / f'{name}.log').write_text(result.stdout + result.stderr, encoding='utf-8')
    if result.returncode:
        raise RuntimeError(f'{name} failed, see {BUILD / (name + ".log")}\n{(result.stdout + result.stderr)[-5000:]}')


def compile_document(job: str) -> None:
    latex = [shutil.which('pdflatex'), '-interaction=nonstopmode', '-halt-on-error', '-file-line-error',
             '-no-shell-escape', f'{job}.tex']
    run(latex, f'{job}-pass-1')
    run([shutil.which('bibtex'), job], f'{job}-bibtex')
    run(latex, f'{job}-pass-2')
    run(latex, f'{job}-pass-3')
    log = (BUILD / f'{job}.log').read_text(encoding='utf-8', errors='replace')
    if 'Rerun to get' in log:   # line numbers and hyperref anchors can need one more pass
        run(latex, f'{job}-pass-4')
        log = (BUILD / f'{job}.log').read_text(encoding='utf-8', errors='replace')
    issues = [line for line in log.splitlines()
              if re.search(r'Overfull \\[hv]box|undefined|multiply defined|Rerun to get', line)]
    if issues:
        raise RuntimeError(f'{job}: resolve layout and reference issues:\n' + '\n'.join(issues))


def source_of(name: str) -> Path:
    """Files generated for the CPC version take precedence over the shared arXiv assets."""
    for base in (CPC, SHARED):
        if (base / name).exists():
            return base / name
    raise FileNotFoundError(name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--keep-assets', action='store_true', help='Do not regenerate the CPC figures and tables.')
    args = parser.parse_args()
    if not (shutil.which('pdflatex') and shutil.which('bibtex')):
        raise SystemExit('Install TeX Live or MiKTeX with pdflatex and bibtex on PATH.')
    if not args.keep_assets:
        import build_cpc_assets
        build_cpc_assets.main()
    tex = (CPC / f'{MAIN}.tex').read_text(encoding='utf-8')
    si = (CPC / f'{SUPP}.tex').read_text(encoding='utf-8')
    for name, content in ((MAIN, tex), (SUPP, si)):
        if '\u2014' in content or '---' in content or ';' in content:
            raise ValueError(f'Writing rule violated in {name}.tex (em dash or semicolon).')
    report = check_front_matter(tex)
    highlights = check_highlights(CPC / 'highlights.txt')
    numbers = write_si_numbers(tex, si)

    # Stage the sources with the figures and tables that they reference.
    if BUILD.exists():
        shutil.rmtree(BUILD)
    BUILD.mkdir(parents=True)
    staged = []
    for name in (f'{MAIN}.tex', f'{SUPP}.tex', 'references.bib', 'si-numbers.tex'):
        shutil.copyfile(CPC / name, BUILD / name)
        staged.append(name)
    needed = set()
    for content in (tex, si):
        needed.update(n if Path(n).suffix else n + '.tex' for n in re.findall(r'\\input\{([^}]+)\}', content))
        needed.update(re.findall(r'\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}', content))
    needed.discard('si-numbers.tex')
    for name in sorted(needed):
        (BUILD / name).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source_of(name), BUILD / name)
        staged.append(name)

    compile_document(MAIN)
    compile_document(SUPP)

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    shutil.copyfile(BUILD / f'{MAIN}.pdf', OUT / 'TorchFDTD-CPC-manuscript.pdf')
    shutil.copyfile(BUILD / f'{SUPP}.pdf', OUT / 'TorchFDTD-CPC-supplementary-material.pdf')
    shutil.copyfile(CPC / 'highlights.txt', OUT / 'TorchFDTD-CPC-highlights.txt')
    try:
        import docx
        document = docx.Document()
        document.add_heading('Highlights', level=1)
        for line in highlights:
            document.add_paragraph(line, style='List Bullet')
        document.save(OUT / 'TorchFDTD-CPC-highlights.docx')
    except ImportError:
        print('python-docx is not installed, so only the plain-text highlights were written.')
    with ZipFile(OUT / 'TorchFDTD-CPC-latex-source.zip', 'w', ZIP_DEFLATED) as archive:
        for name in staged:
            archive.write(BUILD / name, name)
        for job in (MAIN, SUPP):
            archive.write(BUILD / f'{job}.bbl', f'{job}.bbl')
    # CPiP submissions also upload the program files: source, README, tests and the validation records that serve as
    # sample input and output. The archive is the committed HEAD, so uncommitted edits are never shipped.
    head = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    subprocess.run(['git', 'archive', '--format=zip', f'--prefix=TorchFDTD-{head}/',
                    '-o', str(OUT / 'TorchFDTD-CPC-program-files.zip'), 'HEAD'], cwd=ROOT, check=True)
    print(f'Program files: TorchFDTD-CPC-program-files.zip from commit {head}')
    print('Supplementary Sections:', ', '.join(f'{v} {k}' for k, v in numbers.items()))
    print('CPC checks:', report, f'highlights={len(highlights)}')
    print(f'Submission files: {OUT}')
    pending = re.findall(r'\\authorcheck\{([^}]*)\}', tex.split('\\newcommand{\\authorcheck}')[1].split('\n', 1)[1])
    for item in pending:
        print('AUTHOR ITEM TO COMPLETE BEFORE SUBMISSION:', item[:120])


if __name__ == '__main__':
    main()
