"""Compile the canonical LaTeX manuscript and create a portable source bundle."""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import shutil
import subprocess
from zipfile import ZIP_DEFLATED, ZipFile

from build_paper_assets import build_assets
from build_paper_story_figures import build_story_figures

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / 'docs/paper'


def run(command: list[str], cwd: Path, name: str) -> None:
    result = subprocess.run(command, cwd=cwd, capture_output=True,
                            text=True, encoding='utf-8', errors='replace')
    output = result.stdout + result.stderr
    log = cwd / f'{name}.log'
    log.write_text(output, encoding='utf-8')
    if result.returncode:
        raise RuntimeError(f'{name} failed. See {log}\n{output[-7000:]}')


def build_arxiv_bundle(files: list[Path], bbl: Path) -> Path:
    """arXiv source: manuscript, bibliography with its compiled bbl, figures, tables and ancillary records.

    arXiv does not run BibTeX, so the bbl generated by this build is shipped under the main file's job
    name. The ancillary directory carries the validation records that the figures were typeset from and
    the figure generator, which locates them there when docs/validation is absent.
    """
    import json
    output = ROOT / 'output/torchfdtd-arxiv.zip'
    records = set()
    for manifest in ('asset-provenance.json', 'story-figure-provenance.json'):
        inputs = json.loads((PAPER / manifest).read_text(encoding='utf-8'))['inputs']
        for name in inputs:
            # keep sub-folders such as g3/ and meep_comparison/ so the scripts find their records under anc/
            records.add(name.removeprefix('docs/validation/'))
    records.add('color-router-rcwa-3060.json')
    with ZipFile(output, 'w', ZIP_DEFLATED) as archive:
        for path in files:
            if path.suffix in {'.tex', '.bib', '.pdf'}:
                archive.write(path, path.relative_to(PAPER).as_posix())
        archive.write(bbl, 'manuscript.bbl')
        for name in sorted(records):
            archive.write(ROOT / 'docs/validation' / name, f'anc/{name}')
        archive.write(ROOT / 'scripts/build_paper_story_figures.py', 'anc/build_paper_story_figures.py')
        archive.write(ROOT / 'scripts/build_paper_assets.py', 'anc/build_paper_assets.py')
        for name in ('torchfdtd_router.py', 'torcwa_reference.py', 'README.md'):
            archive.write(ROOT / 'benchmarks/color_router_rcwa' / name, f'anc/color_router_rcwa/{name}')
        for manifest in ('asset-provenance.json', 'story-figure-provenance.json'):
            archive.write(PAPER / manifest, f'anc/{manifest}')
        archive.writestr('anc/README.txt',
            'Ancillary files of the TorchFDTD manuscript.\n\n'
            'JSON and NPZ records: the validation records and saved field arrays behind every figure and generated table.\n'
            'asset-provenance.json, story-figure-provenance.json: SHA-256 hashes of the records each script read.\n'
            'From the unpacked directory,\n'
            '    python anc/build_paper_assets.py          regenerates the measured figures and every file in tables/\n'
            '    python anc/build_paper_story_figures.py   regenerates the schematic, the field-map figures and the rest\n'
            'Both need NumPy and Matplotlib and read only these records. They run no solver.\n'
            'color_router_rcwa/: drivers of the colour-router cross-check (Section 6.3). They need TorchFDTD,\n'
            'TORCWA, a CUDA device and the published mask and model of arXiv:2608.13019, see its README.\n'
            'Table 2 and the remaining in-text values come from records in docs/validation of the TorchFDTD repository.\n')
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--keep-assets', action='store_true',
                        help='Use the checked-in figure and table assets without regenerating them.')
    args = parser.parse_args()
    # pdfLaTeX is the engine arXiv runs, so the checked PDF is the one arXiv will produce.
    engines = {name: shutil.which(name) for name in ('pdflatex', 'bibtex')}
    if not all(engines.values()):
        raise SystemExit('Install TeX Live or MiKTeX with pdflatex and bibtex on PATH.')
    if not args.keep_assets:
        build_assets()
        build_story_figures()
    # Package only dependencies of the current manuscript, not retired drafts.
    names = {'manuscript.tex', 'references.bib', 'README.md',
             'asset-provenance.json', 'story-figure-provenance.json'}
    queue = ['manuscript.tex']
    while queue:
        content = (PAPER / queue.pop()).read_text(encoding='utf-8')
        for name in re.findall(r'\\input\{([^}]+)\}', content):
            name = name if Path(name).suffix else name + '.tex'
            if name not in names:
                names.add(name)
                queue.append(name)
        names.update(re.findall(r'\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}', content))
    files = [PAPER / name for name in sorted(names)]
    for path in files:
        if path.suffix in {'.tex', '.bib'}:
            content = path.read_text(encoding='utf-8')
            if '\u2014' in content or '---' in content or '\\textemdash' in content or ';' in content:
                raise ValueError(f'Manuscript writing rule violated in {path.name}')

    # The staging directory also checks that the source bundle is self-contained.
    build = ROOT / 'tmp/latex'
    build.mkdir(parents=True, exist_ok=True)
    for path in files:
        destination = build / path.relative_to(PAPER)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, destination)
    job = 'torchfdtd-manuscript'
    latex = [engines['pdflatex'], '-interaction=nonstopmode', '-halt-on-error',
             '-file-line-error', '-no-shell-escape', f'-jobname={job}', 'manuscript.tex']
    run(latex, build, 'latex-pass-1')
    run([engines['bibtex'], job], build, 'bibtex-pass')
    run(latex, build, 'latex-pass-2')
    run(latex, build, 'latex-pass-3')
    log = (build / f'{job}.log').read_text(encoding='utf-8', errors='replace')
    issues = [line for line in log.splitlines()
              if re.search(r'Overfull \\[hv]box|undefined|multiply defined|Rerun to get', line)]
    if issues:
        raise RuntimeError('Resolve manuscript layout/reference issues before delivery:\n'+'\n'.join(issues))

    output = ROOT / 'output/pdf'
    output.mkdir(parents=True, exist_ok=True)
    for destination in (PAPER / f'{job}.pdf', output / f'{job}.pdf'):
        shutil.copyfile(build / f'{job}.pdf', destination)
    bundle = ROOT / 'output/torchfdtd-latex-source.zip'
    with ZipFile(bundle, 'w', ZIP_DEFLATED) as archive:
        for path in files:
            archive.write(path, path.relative_to(PAPER).as_posix())
    arxiv = build_arxiv_bundle(files, build / f'{job}.bbl')
    print(f'Compiled PDF: {output / (job+".pdf")}')
    print(f'Portable LaTeX source: {bundle}')
    print(f'arXiv submission bundle: {arxiv}')
    print('Reference and overfull-box checks passed. Render the PDF for visual review.')


if __name__=='__main__':
    main()
