"""Typeset paper assets from recorded native measurements, without running a solver."""
from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

import build_paper_story_figures as style

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / 'docs/paper'
DATA = ROOT / 'docs/validation'
if not DATA.is_dir():
    # arXiv ancillary layout: records and this script under anc/, figures/ and tables/ at the root
    DATA = ROOT / 'anc'
    PAPER = ROOT


def write_table(name: str, caption: str, header: str, rows: list[str], columns: str = '@{}lrrrr@{}') -> None:
    content = '\n'.join([
        '% Generated by scripts/build_paper_assets.py from native validation JSON.',
        r'\begin{table}[tbp]', r'\centering', r'\small',
        r'\renewcommand{\arraystretch}{1.15}',
        r'\caption{' + caption + '}', r'\label{tab:' + name + '}',
        r'\begin{tabular}{' + columns + '}', r'\toprule', header + r' \\',
        r'\midrule', *rows, r'\bottomrule', r'\end{tabular}', r'\end{table}', '',
    ])
    (PAPER / 'tables' / f'{name}.tex').write_text(content, encoding='utf-8')


def write_stacked_table(name: str, caption: str, blocks: list[tuple[str, str, list[str]]]) -> None:
    """One float holding one tabular per (columns, header, rows) block, for measurements whose columns differ."""
    content = ['% Generated by scripts/build_paper_assets.py from native validation JSON.',
               r'\begin{table}[tbp]', r'\centering', r'\small',
               r'\renewcommand{\arraystretch}{1.15}',
               r'\caption{' + caption + '}', r'\label{tab:' + name + '}']
    for index, (columns, header, rows) in enumerate(blocks):
        if index:
            content.append(r'\par\vspace{6pt}')
        content += [r'\begin{tabular}{' + columns + '}', r'\toprule', header + r' \\',
                    r'\midrule', *rows, r'\bottomrule', r'\end{tabular}']
    content += [r'\end{table}', '']
    (PAPER / 'tables' / f'{name}.tex').write_text('\n'.join(content), encoding='utf-8')


def native_fused(case: dict) -> dict:
    """Median of the native fused engine, named photonweave_fused in records made before the rename."""
    medians = case['medians']
    return medians['torchfdtd_fused'] if 'torchfdtd_fused' in medians else medians['photonweave_fused']


def native_error(entry: dict) -> dict:
    return entry['torchfdtd_relative_l2'] if 'torchfdtd_relative_l2' in entry else entry['photonweave_relative_l2']


def gpu_label(record: dict) -> str:
    name = record['hardware']['gpu'] if 'hardware' in record else record['cases'][0]['sample_summary']['gpu']
    if 'A100' in name:
        return 'an A100 80GB PCIe'
    if '5880' in name:
        return 'an RTX 5880 Ada'
    return name


def sci(value: float, digits: int) -> str:
    mantissa, exponent = f'{value:.{digits}e}'.split('e')
    return mantissa + r'\times10^{' + str(int(exponent)) + '}'


def ceil_sig(value: float, digits: int) -> float:
    """Smallest number with the given significant digits that is not below value, for 'within' statements."""
    scale = 10 ** (digits - 1 - math.floor(math.log10(value)))
    return math.ceil(value * scale - 1e-9) / scale


RANK_WORDS = {4: 'four', 8: 'eight', 12: 'twelve', 16: 'sixteen'}


def fastest_meep(records: list[dict]) -> dict:
    """The Meep throughput record of the workstation whose rank count solves every scene fastest."""
    assert all('float64' in r['environment']['precision'] for r in records)
    best = min(records, key=lambda r: sum(c['median_wall_seconds'] for c in r['cases']))
    for case in best['cases']:
        for key in ('median_wall_seconds', 'median_loop_seconds'):
            assert all(case[key] <= other[key] for r in records for other in r['cases'] if other['name'] == case['name'])
    return best


def precision_assets(torch_: dict, records: list[dict]) -> None:
    """Double-precision forward solves of the sphere scenes: Meep on the workstation CPU at its fastest timed rank
    count against TorchFDTD on the A100. Writes the table and the macros of the text."""
    gpu = {(c['name'], c['precision']): c for c in torch_['cases']}
    meep = fastest_meep(records)
    ranks = sorted({r['environment']['mpi_processes'] for r in records})
    fastest, words = meep['environment']['mpi_processes'], RANK_WORDS
    rows, ratios64, ratios32, cost = [], [], [], []
    for case in sorted((c for c in meep['cases'] if c['name'].startswith('sphere')), key=lambda c: c['cells']):
        name = case['name']
        t64, t32 = gpu[(name, 'float64')], gpu[(name, 'float32')]
        assert t64['cells'] == case['cells'] and t64['steps'] == case['steps']
        r64 = case['median_wall_seconds'] / t64['median_wall_seconds']
        r32 = case['median_wall_seconds'] / t32['median_wall_seconds']
        ratios64.append(r64)
        ratios32.append(r32)
        cost.append(t64['median_wall_seconds'] / t32['median_wall_seconds'])
        rows.append(f"${name.split('-')[1]}^{{3}}$ & {case['median_wall_seconds']:.2f} & {t64['median_wall_seconds']:.3f} & "
                    f"{r64:.0f} & {t32['median_wall_seconds']:.3f} & {r32:.0f} " + r'\\')
    write_table('cpu-gpu-precision',
        'Full forward solves of the sphere scenes of Table~\\ref{tab:cross-solver-speed} at 800 steps. Meep runs in double '
        f'precision on {words[fastest]} MPI ranks of the i7-12700 workstation CPU, the fastest of the '
        f"{', '.join(str(n) for n in ranks[:-1])} and {ranks[-1]} ranks timed on it, and TorchFDTD on one A100 80GB PCIe in "
        'double and in single precision. Each time is the median of three warmed solves, and each ratio divides the Meep '
        'time by the TorchFDTD time in the column before it.',
        r'Grid & \shortstack{Meep, CPU\\FP64 (s)} & \shortstack{TorchFDTD\\FP64 (s)} & Ratio & \shortstack{TorchFDTD\\FP32 (s)} & Ratio',
        rows, columns='@{}lrrrrr@{}')
    values = [
        '% Generated from docs/validation/paper_review/torchfdtd-precision-a100.json and docs/validation/cross_solver/meep_throughput_ranks*.json.',
        r'\newcommand{\PrecisionMeepRanks}{' + words[fastest] + '}',
        r'\newcommand{\PrecisionRatioMin}{' + f'{min(ratios64):.0f}' + '}',
        r'\newcommand{\PrecisionRatioMax}{' + f'{max(ratios64):.0f}' + '}',
        r'\newcommand{\PrecisionSingleRatioMin}{' + f'{min(ratios32):.0f}' + '}',
        r'\newcommand{\PrecisionSingleRatioMax}{' + f'{max(ratios32):.0f}' + '}',
        r'\newcommand{\PrecisionDoubleCost}{' + f'{min(cost):.1f}' + '}', '',
    ]
    assert f'{min(cost):.1f}' == f'{max(cost):.1f}', 'the text quotes one double-precision cost for both grids'
    (PAPER / 'tables/precision-values.tex').write_text('\n'.join(values), encoding='utf-8')


def cross_solver_assets(record: dict, meep: dict) -> None:
    """Two tables and the text macros of the same-workstation Meep and FDTDX comparison. The Meep throughput rows come
    from meep, the record of the rank count that is fastest on the workstation CPU."""
    label = {'torchfdtd': 'TorchFDTD', 'fdtdx': 'FDTDX', 'meep': 'Meep'}
    method = {'torchfdtd': 'closed TFSF box, scattered-field planes',
              'fdtdx': 'one-way plane source, empty run subtracted',
              'meep': 'current sheet, empty run subtracted'}
    slab, sphere, sphere_fixture = record['slab'], record['sphere'], record['fixtures']['sphere']
    rows = [f"{label[s]} & {method[s]} & ${sci(slab['solvers'][s]['max_T_absolute_error'], 2)}$ & "
            f"${sci(slab['solvers'][s]['max_R_absolute_error'], 2)}$ & {100*sphere['solvers'][s]['max_relative_error']:.2f} " + r'\\'
            for s in label]
    pair_t = max(v['T_max_abs'] for v in slab['pairwise'].values())
    pair_r = max(v['R_max_abs'] for v in slab['pairwise'].values())
    pair_sphere = max(v['max_relative'] for v in sphere['pairwise'].values())
    rows += [r'\midrule', r'\multicolumn{2}{@{}l}{Largest pairwise difference} & ' + f"${sci(pair_t, 2)}$ & ${sci(pair_r, 2)}$ & {100*pair_sphere:.2f} " + r'\\']
    write_table('cross-solver-accuracy',
        'TorchFDTD, FDTDX 0.6.2 and Meep 1.34 on one workstation, with its i7-12700 CPU for Meep and its RTX 3060 for the '
        'two GPU solvers. The slab columns are the maximum absolute errors of the transmission and '
        'reflection spectra against Eq.~\\eqref{eq:slab} over 31 wavelengths. The sphere column is the maximum relative '
        f"cross-section error of a sphere of index {sphere_fixture['sphere']['index']} and radius {sphere_fixture['sphere']['radius_um']}~\\micron{{}} "
        f"against the Mie series over nine wavelengths at a {sphere_fixture['mesh_um']}~\\micron{{}} mesh, with the source and "
        'monitor method of each solver. The last row is the largest difference between any two solvers. Meep propagates '
        'double-precision fields, the other two single precision.',
        r'Solver & Sphere source and monitors & \shortstack{Slab $|\Delta T|$\\max} & \shortstack{Slab $|\Delta R|$\\max} & \shortstack{Sphere\\error (\%)}',
        rows, columns='@{}llrrr@{}')

    cases = record['throughput']['cases']
    meep_cases = {c['name']: c for c in meep['cases']}
    assert meep_cases.keys() == cases.keys()
    solver = lambda case_name, s: meep_cases[case_name] if s == 'meep' else cases[case_name]['solvers'][s]
    forward = []
    for case_name, case in cases.items():
        if not case_name.startswith('sphere'):
            continue
        for s in label:
            r = solver(case_name, s)
            peak = r.get('peak_allocated_bytes', r.get('peak_bytes_in_use'))
            forward.append(f"${case['shape'][0]}^3$ & {label[s]} & {r['median_wall_seconds']:.3f} & {r['median_loop_seconds']:.3f} & "
                           f"${sci(r['cell_steps_per_second_stepping'], 2)}$ & {'CPU' if peak is None else f'{peak/2**20:.0f}'} " + r'\\')
    adjoint = record['adjoint']
    reference = adjoint['solvers']['torchfdtd_checkpointed']
    adjoint_rows = []
    for key, name in [('torchfdtd_checkpointed', 'TorchFDTD, checkpointed, 2 checkpoints'),
                      ('fdtdx_checkpointed', 'FDTDX, checkpointed, 2 checkpoints'),
                      ('fdtdx_reversible', 'FDTDX, reversible')]:
        r = adjoint['solvers'][key]
        peak = r.get('peak_allocated_bytes', r.get('peak_bytes_in_use'))
        pair = adjoint['pairwise'].get(f'torchfdtd_checkpointed_vs_{key}')
        difference = 'reference' if pair is None else f"${sci(pair['gradient_relative_l2'], 1)}$"
        adjoint_rows.append(f"{name} & {r['median_wall_seconds']:.3f} & {peak/2**20:.0f} & {difference} " + r'\\')
    write_stacked_table('cross-solver-speed',
        'Forward throughput and time to gradient on the workstation of Table~\\ref{tab:cross-solver-accuracy}. '
        'The forward rows are the sphere scene at 800 steps as medians of three warmed solves, where the full solve includes '
        'setup and the final field transfer and the stepping column is the time-stepping loop alone. The adjoint rows are the '
        'permittivity gradient of a periodic dielectric slab at $64^{3}$ cells and 128 steps, and the last column is the '
        r'relative $L_2$ difference of each gradient from the TorchFDTD gradient. Meep ran in double precision on '
        f"{RANK_WORDS[meep['environment']['mpi_processes']]} MPI ranks, its fastest setting on this CPU, and its adjoint is "
        'excluded because it is a frequency-domain method. '
        'The GPU solvers ran in single precision.',
        [('@{}llrrrr@{}', r'Grid & Solver & \shortstack{Full solve\\(s)} & \shortstack{Stepping\\(s)} & \shortstack{Cell-steps/s\\stepping} & \shortstack{Peak device\\(MiB)}', forward),
         ('@{}lrrr@{}', r'Adjoint method & \shortstack{Time to\\gradient (s)} & \shortstack{Peak device\\(MiB)} & \shortstack{Gradient relative\\$L_2$ difference}', adjoint_rows)])

    torch_cases = {n: c['solvers']['torchfdtd'] for n, c in cases.items()}
    ratio = {s: {k: [solver(n, s)[k] / torch_cases[n][k] for n in cases]
                 for k in ('median_wall_seconds', 'median_loop_seconds')} for s in ('fdtdx', 'meep')}
    gradient_difference = max(adjoint['pairwise'][f'torchfdtd_checkpointed_vs_{k}']['gradient_relative_l2']
                              for k in ('fdtdx_checkpointed', 'fdtdx_reversible'))
    values = [
        '% Generated from docs/validation/cross_solver_3060.json and the fastest docs/validation/cross_solver/meep_throughput_ranks*.json.',
        r'\newcommand{\CrossMeepRanks}{' + RANK_WORDS[meep['environment']['mpi_processes']] + '}',
        r'\newcommand{\CrossSlabPairT}{' + sci(ceil_sig(pair_t, 2), 1) + '}',
        r'\newcommand{\CrossSpherePair}{' + f'{ceil_sig(100*pair_sphere, 1):.1f}' + '}',
        r'\newcommand{\CrossFdtdxStepMin}{' + f"{min(ratio['fdtdx']['median_loop_seconds']):.1f}" + '}',
        r'\newcommand{\CrossFdtdxStepMax}{' + f"{max(ratio['fdtdx']['median_loop_seconds']):.1f}" + '}',
        r'\newcommand{\CrossFdtdxFullMin}{' + f"{min(ratio['fdtdx']['median_wall_seconds']):.1f}" + '}',
        r'\newcommand{\CrossFdtdxFullMax}{' + f"{max(ratio['fdtdx']['median_wall_seconds']):.1f}" + '}',
        r'\newcommand{\CrossMeepFullMin}{' + f"{min(ratio['meep']['median_wall_seconds']):.0f}" + '}',
        r'\newcommand{\CrossMeepFullMax}{' + f"{max(ratio['meep']['median_wall_seconds']):.0f}" + '}',
        r'\newcommand{\CrossMeepStepMin}{' + f"{min(ratio['meep']['median_loop_seconds']):.0f}" + '}',
        r'\newcommand{\CrossMeepStepMax}{' + f"{max(ratio['meep']['median_loop_seconds']):.0f}" + '}',
        r'\newcommand{\CrossAdjointCheckpointRatio}{' + f"{adjoint['solvers']['fdtdx_checkpointed']['median_wall_seconds']/reference['median_wall_seconds']:.0f}" + '}',
        r'\newcommand{\CrossAdjointReversibleRatio}{' + f"{adjoint['solvers']['fdtdx_reversible']['median_wall_seconds']/reference['median_wall_seconds']:.1f}" + '}',
        r'\newcommand{\CrossGradientDiff}{' + sci(ceil_sig(gradient_difference, 2), 1) + '}', '',
    ]
    (PAPER / 'tables/cross-solver-values.tex').write_text('\n'.join(values), encoding='utf-8')


# Meep throughput records of the workstation, one per MPI rank count, with the reruns on an otherwise idle host
MEEP_RANKS = ('ranks4', 'ranks8', 'ranks12', 'ranks16', 'ranks4_quiet', 'ranks12_quiet')


def build_assets() -> None:
    (PAPER / 'figures').mkdir(parents=True, exist_ok=True)
    (PAPER / 'tables').mkdir(parents=True, exist_ok=True)
    names = ('flux', 'batch', 'cuda-kernels', 'open-source-flaport', 'tensor-batch', 'cohorts', 'vector-sources', 'oneway-sources', 'oneway-slab', 'ensembles', 'design-throughput', 'ensemble-before', 'tfsf-sources', 'tfsf-sphere', 'tfsf-sphere-finer', 'tfsf-sphere-long', 'spectral-ensembles', 'graph-ensembles', 'selective-monitors', 'rectilinear-ensembles', 'geometry-ensembles', 'grouped-ensembles', 'cross_solver_3060', 'flux-slab-project', 'precision-a100', *MEEP_RANKS)
    # The manuscript reports its timings on the A100. The RTX 5880 originals stay in docs/validation,
    # and a caption always names the GPU of the record it was built from.
    files = {name: name for name in names}
    files['flux-slab-project'] = 'paper_review/flux-slab-project'   # geometry of the slab of Fig. 2
    files['precision-a100'] = 'paper_review/torchfdtd-precision-a100'
    files.update({name: f'cross_solver/meep_throughput_{name}' for name in MEEP_RANKS})
    for name in ('batch', 'open-source-flaport', 'tensor-batch', 'ensembles', 'tfsf-sphere', 'tfsf-sphere-finer', 'tfsf-sphere-long'):
        if (DATA / f'{name}-a100.json').exists():
            files[name] = f'{name}-a100'
    raw = {name: (DATA / f'{files[name]}.json').read_bytes() for name in names}
    data = {name: json.loads(value) for name, value in raw.items()}
    flux, batch, cuda = (data[name] for name in ('flux', 'batch', 'cuda-kernels'))

    style.apply_style()
    metadata = style.METADATA
    wl = np.asarray(flux['wavelength_um'])
    order = np.argsort(wl)
    exact_t = np.asarray(flux['analytic_T'])
    fig = plt.figure(figsize=(style.WIDTH, 3.5))
    grid = fig.add_gridspec(2, 2, height_ratios=[0.45, 1])
    geometry = fig.add_subplot(grid[0, :])
    style.flux_slab_geometry(geometry, data['flux-slab-project'])
    style.panel(geometry, 'a', 'Geometry')
    axes = [fig.add_subplot(grid[1, 0]), fig.add_subplot(grid[1, 1])]
    for key, exact, color, marker in [('T', exact_t, style.BLUE, 'o'), ('R', 1-exact_t, style.ORANGE, 's')]:
        values = np.asarray(flux[key])
        # small hollow markers under the analytic line, so both stay visible
        axes[0].plot(wl[order], values[order], ls='none', marker=marker, color=color, ms=2.4,
                     mfc='white', mew=0.8, zorder=2, label=f'TorchFDTD {key}')
        axes[0].plot(wl[order], exact[order], color=style.INK, lw=0.8, zorder=3,
                     label='analytic' if key == 'T' else None)
        axes[0].annotate(key, (wl[order][-1], values[order][-1]), (7, 0), textcoords='offset points',
                         va='center', fontsize=7.5, color=color, weight='bold')
    # |T - analytic| and |R - analytic| coincide within the energy residual: draw one as a line, the other as markers
    error_t = np.abs(np.asarray(flux['T']) - exact_t)
    error_r = np.abs(np.asarray(flux['R']) - (1 - exact_t))
    axes[1].plot(wl[order], error_t[order], color=style.BLUE, lw=1.4, zorder=2, label='|T $-$ analytic|')
    axes[1].plot(wl[order], error_r[order], ls='none', marker='s', color=style.ORANGE, ms=2.2,
                 mfc='white', mew=0.8, zorder=3, label='|R $-$ analytic|')
    residual = np.abs(np.asarray(flux['R']) + np.asarray(flux['T']) - 1)
    axes[1].plot(wl[order], residual[order], color=style.TEAL, lw=1.1, marker='.', ms=3,
                 label='|R + T $-$ 1|')
    axes[1].annotate('equal within the\nenergy residual', (wl[order][15], error_t[order][15]), (0, 7),
                     textcoords='offset points', ha='center', va='bottom', fontsize=6.2, color=style.MUTED)
    axes[0].set(xlabel='Wavelength (µm)', ylabel='Power ratio', ylim=(0, 1.0), xlim=(1.28, 1.86))
    axes[0].set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
    axes[1].set(xlabel='Wavelength (µm)', ylabel='Absolute error', yscale='log', xlim=(1.28, 1.82))
    axes[1].set_ylim(3e-8, 3e-2)
    axes[0].legend(loc='center right', bbox_to_anchor=(1.0, 0.52), handlelength=1.5)
    axes[1].legend(loc='center right', bbox_to_anchor=(1.0, 0.52))
    style.panel(axes[0], 'b', 'Slab transmission and reflection, 31 samples')
    style.panel(axes[1], 'c', 'Error against the analytic spectra and energy residual')
    fig.tight_layout(w_pad=2.2, h_pad=1.0)
    fig.savefig(PAPER / 'figures/flux-validation.pdf', metadata=metadata, bbox_inches='tight', pad_inches=0.04)
    plt.close(fig)

    sphere = data['tfsf-sphere']['cases'] + data['tfsf-sphere-finer']['cases']
    sphere.sort(key=lambda c: -c['project']['region']['mesh'])   # coarse to fine
    fig, panels = plt.subplots(1, 3, figsize=(style.WIDTH, 2.35), gridspec_kw={'width_ratios': [0.8, 1, 1]})
    style.sphere_geometry(panels[0], sphere[0]['project'])
    style.panel(panels[0], 'a', 'Geometry, z = 0')
    axes = panels[1:]
    markers = ['o', 's', 'D', '^']
    for case, color, marker in zip(sphere, style.BLUES, markers):
        wl=np.asarray(case['wavelength_um']);order=np.argsort(wl)
        actual=np.asarray(case['scattering_cross_section_um2'])
        exact=np.asarray(case['mie_cross_section_um2'])
        label=f"$h$ = {case['project']['region']['mesh']:g} µm"
        axes[0].plot(wl[order],actual[order],color=color,label=label,lw=1.2,marker=marker,ms=3.2,mfc='white',mew=0.9)
        axes[1].plot(wl[order],abs(actual/exact-1)[order],color=color,label=label,lw=1.2,marker=marker,ms=3.2,mfc='white',mew=0.9)
    axes[0].plot(wl[order],exact[order],color=style.INK,ls=(0,(4,2)),label='Mie series',lw=1.0,zorder=0)
    axes[0].set(xlabel='Wavelength (µm)',ylabel='Scattering cross section (µm$^2$)', xlim=(1.28, 1.82))
    axes[1].set(xlabel='Wavelength (µm)',ylabel='Relative error',yscale='log', xlim=(1.28, 1.82), ylim=(1e-4, 3e-1))
    axes[0].legend(loc='upper right', handlelength=2.0)
    style.panel(axes[0], 'b', 'Cross section by mesh step')
    style.panel(axes[1], 'c', 'Relative error against the Mie series')
    fig.tight_layout(w_pad=1.6)
    style.align_square_title(fig, panels[0], panels[1], 'a', 'Geometry, z = 0')
    fig.savefig(PAPER/'figures/tfsf-sphere.pdf',metadata=metadata, bbox_inches='tight', pad_inches=0.04)
    plt.close(fig)
    sphere += data['tfsf-sphere-long']['cases']
    write_table('tfsf-sphere',
        f"Closed-box TFSF sphere scattering on {gpu_label(data['tfsf-sphere'])}. The maximum relative cross-section "
        'error is taken over nine wavelengths. Physical domain and PML thickness stay fixed. '
        'The final row doubles the physical duration. The error sequence is not monotonic.',
        r'$h$ ($\mu$m) & Grid & \shortstack{Time\\(fs)} & \shortstack{Max error\\(\%)} & \shortstack{Empty box\\($\mu$m$^2$)}',
        [f"{c['project']['region']['mesh']:g} & ${c['sample_summary']['shape'][0]}^3$ & "
         f"{240 if c['sample_summary']['duration_fs']>200 else 120} & "
         f"{100*c['max_relative_error']:.4f} & "
         '$'+f"{c['max_empty_box_cross_section_um2']:.2e}".replace('e-0',r'\times10^{-').replace('e-',r'\times10^{-')+'}$ '+r'\\'
         for c in sphere])

    rows = batch['measurements']
    labels = [f"{r['backend'].upper()}\n{r['workers']} worker" + ('s' if r['workers']>1 else '') for r in rows]
    colors = [style.GREY if r['backend'] == 'cpu' else style.BLUE for r in rows]
    fig, axes = plt.subplots(1, 2, figsize=(style.WIDTH, 2.2))
    for ax, key, ylabel, letter, ttl in zip(axes,
            ['median_seconds', 'cases_per_second'],
            ['Four-case wall time (s)', 'Cases per second'], ['a', 'b'],
            ['Wall time, logarithmic axis', 'Throughput']):
        values = [r[key] for r in rows]
        bars = ax.bar(labels, values, color=colors, width=0.62, linewidth=0)
        ax.set_ylabel(ylabel)
        style.panel(ax, letter, ttl)
        style.ygrid(ax)
        ax.tick_params(axis='x', length=0)
        if key=='median_seconds':
            ax.set(yscale='log', ylim=(0.5, 200))
            ax.bar_label(bars, labels=[f'{v:.2f}' for v in values], padding=2.5, fontsize=6.5)
            ax.annotate(f"{rows[1]['speedup_vs_cpu_1']:.0f}$\\times$", (0.5, 7.5), ha='center', va='center',
                        fontsize=6.6, color=style.MUTED)
            ax.annotate('', (1, 1.55), (0, 38), arrowprops=dict(arrowstyle='-|>', color=style.LINE, lw=0.6,
                        mutation_scale=6, connectionstyle='arc3,rad=-0.25'))
        else:
            ax.set_ylim(0, 4.3)
            ax.bar_label(bars, labels=[f'{v:.2f}' for v in values], padding=2.5, fontsize=6.5)
    fig.tight_layout(w_pad=2.2)
    fig.savefig(PAPER / 'figures/batch-throughput.pdf', metadata=metadata, bbox_inches='tight', pad_inches=0.04)
    plt.close(fig)

    write_table('batch',
        'Independent four-case sphere ensembles. Medians of three measured batches after warm-up, '
        'including setup, transfers, worker communication and allocator cleanup. Initial process startup is excluded. '
        'The CPU baseline is the native NumPy implementation.',
        r'Backend & Workers & \shortstack{Batch wall\\time (s)} & Cases/s & \shortstack{Speedup vs\\NumPy CPU}',
        [f"{r['backend'].upper()} & {r['workers']} & {r['median_seconds']:.4f} & "
         f"{r['cases_per_second']:.4f} & ${r['speedup_vs_cpu_1']:.2f}\\times$ " + r'\\' for r in rows])

    write_table('cuda-kernels',
        'Paired native CUDA implementations on RTX 5880. Each value is a median over three measured runs '
        'after warm-up. The reference uses the existing PyTorch CUDA graph. Full wall time includes setup and '
        'final transfers but excludes initial context creation and compilation.',
        r'Grid & \shortstack{Reference loop\\(ms)} & \shortstack{Fused loop\\(ms)} & \shortstack{Loop\\speedup} & \shortstack{Full-wall\\speedup}',
        [f"${c['shape'][0]}^3$ & {1000*c['median']['torch']['loop_seconds']:.1f} & "
         f"{1000*c['median']['fused']['loop_seconds']:.1f} & ${c['loop_speedup']:.2f}\\times$ & "
         f"${c['wall_speedup']:.2f}\\times$ " + r'\\' for c in cuda['cases']])

    write_table('open-source',
        f"Eight forward fixtures on {gpu_label(data['open-source-flaport'])}. The external baseline is flaport/fdtd 0.2.2 "
        'with an added CUDA Graph adapter. Values are medians of three warmed full solves. '
        'The last column is point-trace relative L2 difference in percent, not analytic error. '
        'The PML interface stencils differ and final fields are not identical.',
        r'Fixture, grid & \shortstack{Upstream graph\\(ms)} & \shortstack{Native fused\\(ms)} & Speedup & \shortstack{Trace L2\\(\%)}',
        [f"{c['name'].capitalize()}, ${c['shape'][0]}^3$ & "
         f"{1000*c['medians']['flaport_graph']['wall_seconds']:.2f} & "
         f"{1000*native_fused(c)['wall_seconds']:.2f} & "
         f"${c['medians']['flaport_graph']['wall_seconds']/native_fused(c)['wall_seconds']:.2f}\\times$ & "
         f"{100*max(native_error(e)['trace'] for e in c['errors']):.4f} " + r'\\'
         for c in data['open-source-flaport']['cases']])

    write_table('tensor-batch',
        f"Native sphere ensembles on {gpu_label(data['tensor-batch'])} with a real CUDA batch axis. Full wall times include "
        'setup, transfers and scalar objective evaluation. Final E/H arrays and point traces '
        'match independent native runs bitwise. Values below unity in the last column are slowdowns.',
        r'Grid, cases & \shortstack{Sequential\\(ms)} & \shortstack{Tensor cohort\\(ms)} & Cases/s & Speedup',
        [f"${c['shape'][0]}^3$, {c['batch_size']} & "
         f"{1000*c['medians']['sequential_fused']['wall_seconds']:.2f} & "
         f"{1000*c['medians']['tensor']['wall_seconds']:.2f} & "
         f"{c['medians']['tensor']['cases_per_second']:.2f} & "
         f"${c['medians']['sequential_fused']['wall_seconds']/c['medians']['tensor']['wall_seconds']:.2f}\\times$ " + r'\\'
         for c in data['tensor-batch']['cases']])

    write_table('ensembles',
        f"Sixteen-case ensembles on {gpu_label(data['ensembles'])} after a separate cohort-selection experiment. "
        'The external baseline runs graph-adapted flaport/fdtd cases sequentially. '
        'Native execution shares CUDA launches. These are workflow throughput ratios, '
        'not single-solve or upstream fused-batch comparisons. Tuning cost is excluded here '
        'and reported separately in the raw record and text.',
        r'Fixture, grid & Cohort & \shortstack{Upstream\\(s)} & \shortstack{Native batch\\(s)} & Speedup',
        [f"{c['name'].capitalize()}, ${c['shape'][0]}^3$ & {c['tuning']['cohort_size']} & "
         f"{c['medians']['flaport_graph']['wall_seconds']:.3f} & "
         f"{c['medians']['tuned']['wall_seconds']:.3f} & "
         f"${c['medians']['flaport_graph']['wall_seconds']/c['medians']['tuned']['wall_seconds']:.2f}\\times$ " + r'\\'
         for c in data['ensembles']['cases']])

    write_table('design-throughput',
        'Complete seeded differential-evolution loops on RTX 5880. Each loop includes '
        '64 forward solves and the scalar objective. Three warmed repetitions are summarized '
        'by their medians. Fixed cohorts contain 16 cases at $32^3$ and four cases at $64^3$. '
        'Full optimization histories are identical between modes. There is no adjoint.',
        r'Grid & \shortstack{Independent\\(s)} & \shortstack{Tensor\\(s)} & Speedup & \shortstack{Tensor\\evaluations/s}',
        [f"${c['shape'][0]}^3$ & {c['medians']['sequential']['wall_seconds']:.3f} & "
         f"{c['medians']['tensor']['wall_seconds']:.3f} & "
         f"${c['medians']['sequential']['wall_seconds']/c['medians']['tensor']['wall_seconds']:.2f}\\times$ & "
         f"{c['medians']['tensor']['evaluations_per_second']:.2f} " + r'\\'
         for c in data['design-throughput']['cases']])

    spectral=data['spectral-ensembles']['cases']
    if not all(c['accuracy_pass'] for c in spectral):
        raise ValueError('Spectral ensemble accuracy gates must pass before typesetting speedup claims.')
    write_table('spectral-ensembles',
        'Eight independent cases per row on RTX 5880, with three six-component spatial DFT planes, '
        'nine frequencies, 800 steps and float32. Values are medians of three warmed full solves. '
        'The upstream sequence uses flaport/fdtd 0.2.2 with CUDA Graph and the same new fused DFT adapter. '
        'Both native batch modes use cohorts of four and fused Yee updates. The final column isolates '
        'monitor fusion at that fixed cohort size.',
        r'Fixture, grid & \shortstack{Upstream\\sequence (s)} & \shortstack{Torch DFT\\batch (s)} & \shortstack{Fused DFT\\batch (s)} & \shortstack{Monitor\\speedup}',
        [f"{c['name'].capitalize()}, $" + f"{c['shape'][0]}^3$ & "
         f"{c['medians']['flaport_fused_dft']['wall_seconds']:.3f} & "
         f"{c['medians']['native_batch']['wall_seconds']:.3f} & "
         f"{c['medians']['fused_batch']['wall_seconds']:.3f} & $" +
         f"{c['medians']['native_batch']['wall_seconds']/c['medians']['fused_batch']['wall_seconds']:.2f}\\times$ " + r'\\'
         for c in spectral])

    graph=data['graph-ensembles']['cases']
    if not all(c['accuracy_pass'] for c in graph):
        raise ValueError('Phase and graph ensemble accuracy gates must pass before publication.')
    rows=[]
    for c in graph:
        m=c['medians'];b=m['batch_1']['wall_seconds']
        external=min(m['flaport_1']['wall_seconds'],m['flaport_8']['wall_seconds'])
        rows.append(f"{c['name'].capitalize()}, ${c['shape'][0]}^3$ & {external:.3f} & {b:.3f} & "
                    f"${m['batch_torch_phase']['wall_seconds']/b:.2f}\\times$ & "
                    f"${b/m['batch_8']['wall_seconds']:.2f}\\times$ "+r'\\')
    write_table('graph-ensembles',
        'Phase-kernel and graph-unrolling follow-up with the same eight-case spectral workload on RTX 5880. '
        'Times include preparation of all requested graphs and final transfer. The external sequence receives '
        'the same current observer, using the lower median of its one-step and eight-step options. '
        'Native batch uses cohorts of four and one-step graphs. Phase gain divides the previous phase expression cost '
        'by the new cost. Graph gain divides one-step cost by eight-step cost with the new phase kernel. '
        'Both gains use full wall time and retain values below one.',
        r'Fixture, grid & \shortstack{Upstream\\sequence (s)} & \shortstack{Native\\batch (s)} & \shortstack{Phase\\gain} & \shortstack{Graph\\gain}',rows)

    selective=data['selective-monitors']['cases']
    if not all(c['accuracy_pass'] for c in selective):
        raise ValueError('Selective-output accuracy gates must pass before typesetting.')
    rows=[]
    for c in selective:
        m=c['medians'];b=m['native_batch_flux']['wall_seconds'];full=m['native_batch_full']['wall_seconds']
        upstream=min(m[k]['wall_seconds'] for k in ('flaport_flux_1','flaport_flux_8'))
        rows.append(f"{c['name'].capitalize()}, ${c['shape'][0]}^3$ & {upstream:.3f} & {full:.3f} & {b:.3f} & ${full/b:.2f}\\times$ "+r'\\')
    write_table('selective-monitors',
        'Selective-output ensembles on RTX 5880. Each row uses eight cases, 800 steps, float32 and three planes with 65 frequencies. '
        'Times are medians of three warmed full solves. Native cohorts contain four cases with one-step graphs. '
        'The upstream sequence uses the identical selective observer and the lower median of its one-step and eight-step graphs. '
        'Full output stores six fields and three Poynting components. Flux-only stores the same signed flux with four internal fields. '
        'Selection gain is full-output time divided by flux-only time, with no decimation.',
        r'Fixture, grid & \shortstack{Upstream\\sequence (s)} & \shortstack{Full-output\\batch (s)} & \shortstack{Flux-only\\batch (s)} & \shortstack{Selection\\gain}',rows)

    rectangular=data['rectilinear-ensembles']['cases']
    if not all(c['accuracy_pass'] for c in rectangular):raise ValueError('Rectilinear mesh accuracy gates must pass.')
    rows=[]
    for c in rectangular:
        m=c['medians'];u=m['uniform_batch']['wall_seconds'];b=m['rectangular_batch']['wall_seconds'];s=m['rectangular_sequential']['wall_seconds']
        rows.append(f"{c['name'].capitalize()}, {c['uniform_shape'][0]} & {u:.3f} & {b:.3f} & ${u/b:.2f}\\times$ & ${s/b:.2f}\\times$ "+r'\\')
    write_table('rectilinear-ensembles',
        'Native rectangular mesh ablation on RTX 5880. Each row uses four transverse-invariant cases with the same propagation step, actual time step and flux observables. '
        'The first column gives the longitudinal cell count. Times are medians of three warmed full-wall solves. '
        'Mesh gain compares uniform and rectangular batches. Batch gain compares independent and batch execution at the rectangular mesh. This is not a cross-library ranking.',
        r'Fixture, $N_x$ & \shortstack{Uniform\\batch (s)} & \shortstack{Rectangular\\batch (s)} & \shortstack{Mesh\\gain} & \shortstack{Batch\\gain}',rows)

    geometry=data['geometry-ensembles']['cases']
    if not all(check['passed'] for c in geometry for check in c['checks']):raise ValueError('Geometry output gates must pass.')
    names={'spheres':'Spheres','rotated_boxes':'Rotated boxes','concave_polygons':'Concave polygons','elliptical_sectors':'Elliptical sectors'}
    rows=[]
    for c in geometry:
        a,b=(c['medians'][k] for k in ('unpruned','support_pruned'))
        rows.append(f"{names[c['name']]}, ${c['shape'][0]}^3$ & {a['wall_seconds']:.3f} & {b['wall_seconds']:.3f} & "
                    f"${a['wall_seconds']/b['wall_seconds']:.2f}\\times$ & ${a['voxelize_seconds']/b['voxelize_seconds']:.2f}\\times$ "+r'\\')
    write_table('geometry-ensembles',
        'Native geometry-preparation ablation on RTX 5880. Four cases per row each contain eight solids. '
        'Both modes use identical grids, 800 float32 steps, four-case cohorts and complete outputs. '
        'Medians summarize three warmed alternating repetitions. Full wall includes host preparation, graph capture, stepping and result transfer. '
        'The last column isolates host material preparation. This is not a cross-library comparison or a new CUDA stepping kernel.',
        r'Solids, grid & \shortstack{Unpruned\\batch (s)} & \shortstack{Bounded\\batch (s)} & \shortstack{Full-wall\\gain} & \shortstack{Host prep.\\gain}',rows)

    grouped=data['grouped-ensembles']['cases']
    if not all(c['accuracy_pass'] and all(x['accuracy_pass'] for x in c['checks']) for c in grouped):
        raise ValueError('Mixed-workload output gates must pass.')
    labels={'mixed-mesh-32-48':r'$32^3+48^3$, 800',
            'mixed-mesh-32-64':r'$32^3+64^3$, 800',
            'mixed-duration-32':r'$32^3$, 400/800',
            'mixed-duration-64':r'$64^3$, 400/800'}
    rows=[]
    for c in grouped:
        m=c['medians'];s=m['native_sequential']['wall_seconds'];b=m['native_grouped']['wall_seconds']
        a=min(m[k]['wall_seconds'] for k in ('flaport_graph_1','flaport_graph_8'))
        rows.append(f"{labels[c['name']]} & {a:.3f} & {s:.3f} & {b:.3f} & ${s/b:.2f}\\times$ "+r'\\')
    write_table('grouped-ensembles',
        'Mixed-grid or mixed-duration ensembles on RTX 5880. Each row interleaves 16 cases from four geometry families. '
        'The first column gives grid sizes and time-step counts. All cases retain three six-component planes at nine frequencies. '
        'Medians summarize three warmed repetitions. Full wall includes grouping and all setup and output transfer. '
        'Upstream uses the identical fused observer and the lower median of one-step and eight-step graphs. '
        'Grouped execution uses four-case cohorts and one-step graphs. The last column compares native sequential and grouped execution.',
        r'Grid, steps & \shortstack{Upstream\\sequence (s)} & \shortstack{Native\\sequence (s)} & \shortstack{Native\\grouped (s)} & \shortstack{Native\\gain}',rows)

    mantissa, exponent = f"{flux['max_energy_residual']:.5e}".split('e')
    values = '\n'.join([
        '% Generated from docs/validation/flux.json.',
        r'\newcommand{\SlabTError}{' + f"{flux['max_T_absolute_error']:.8f}" + '}',
        r'\newcommand{\SlabRError}{' + f"{flux['max_R_absolute_error']:.8f}" + '}',
        r'\newcommand{\SlabEnergyError}{' + mantissa + r'\times10^{' + str(int(exponent)) + '}}', '',
    ])
    (PAPER / 'tables/validation-values.tex').write_text(values, encoding='utf-8')
    cross_solver_assets(data['cross_solver_3060'], fastest_meep([data[name] for name in MEEP_RANKS]))
    precision_assets(data['precision-a100'], [data[name] for name in MEEP_RANKS])
    provenance = {
        'description': 'Figures and tables derived from recorded native validation measurements. No solver is run by the paper build.',
        'inputs': {f'docs/validation/{files[name]}.json': hashlib.sha256(value).hexdigest()
                   for name, value in raw.items()},
        'generator': 'scripts/build_paper_assets.py',
    }
    (PAPER / 'asset-provenance.json').write_text(json.dumps(provenance, indent=2)+'\n', encoding='utf-8')


if __name__=='__main__':
    build_assets()
    print('Paper vector figures and TeX tables refreshed from recorded native measurements.')
